### ISSUE TITLE
Container multi buy/assign

### ISSUE THREAD

**Issue by Theo47** [pmotschmann/Evolve#102]
Late game you can get a lot of containers/crates at once so it would be nice to have the option to quickly construct and assign them.

Having to click 1400 times in order to buy and assign all the new containers/crates after buying the "matter compression" research is not fun.

Maybe something similar to the radio buttons on the market or a text box where you specify how many you want to construct/assign? Perhaps unlocked by research?

**Comment by Julepalme** [comment]
Afaik the Ctrl and Shift modifier keys work for buying containers at 10x etc at a time, altho its not immediatly obvious.

**Comment by Theo47** [comment]
Yeah, apparently the ctrl/alt/shift keys do exactly what i was asking.

Thanks for letting me know.
