### ISSUE TITLE
A.R.P.A quality of life improvements

### ISSUE THREAD

**Issue by omsi6** [pmotschmann/Evolve#108]
There were 2 things that I think would be useful for the A.R.P.A projects.

1. There should be a indicator somewhere on the project to show what level it unlocks a new research at. This is because sometimes it can be difficult to figure out what to focus on to unlock more things, without looking at the code.

2. The "X%" buttons above 1% shouldn't show more cost than left in the project. For example, if you've completed 70% of a project and hover over the 100% button, it should only show the cost in materials of 30% of the project, because that's how much more you need to complete it.

**Comment by pmotschmann** [comment]
This was Resolved by 07ac4ec204d0afdd3f7a3ba0ad4d81b2139e36db
