### ISSUE TITLE
[Bug] Building Queue/Log resizes itself once a second

### ISSUE THREAD

**Issue by tankorsmash** [pmotschmann/Evolve#1099]
I only noticed this happening with the latest update, v1.3.11a:

https://github.com/pmotschmann/Evolve/assets/1312390/46c5b7c0-8978-4fc9-b2ee-5c687a5e82f6

It happens when you resize it to make space, where it resizes to fit the content immediately. If you resize it to small, about once a tick it gets slightly larger until it fits all the content.

Chrome Windows 10

**Comment by chipplyman** [comment]
My preference here is that the container would immediately expand to fit the content when you resize it too small, similarly to how it immediately shrinks to fit the content when you resize it too large.

If the linked PR is only controlling whether auto-resize occurs, but does not alter the auto-grow behavior, I don't think it should close this issue.

**Comment by fredden** [comment]
I think this is fixed with the combination of #1100 and #1233. @tankorsmash and @chipplyman, please can you test with version 1.4.0 and confirm if this is suitable for you?

**Comment by tankorsmash** [comment]
@fredden I can confirm on my save this has been fixed. Thank you for the fixes!
