### ISSUE TITLE
Can't build Freight Yards

### ISSUE THREAD

**Issue by redhatturtle** [pmotschmann/Evolve#1134]
Tried on Chomium and Firefox, resources will be subtracted but no building will be constructed.

Save file:
[evolve-2024-05-23-01-44.txt](https://github.com/pmotschmann/Evolve/files/15411638/evolve-2024-05-23-01-44.txt)

**Comment by yarukishi** [comment]
I couldn't find anything in the game code that would specifically cause this issue. Something went wrong when the Containerization technology was researched. Perhaps a very unusual race condition prevented proper update of the global.city object.

Here is a fixed save file that can build a Freight Yard.
[evolve-2024-05-23-01-44-fixed.txt](https://github.com/pmotschmann/Evolve/files/15417259/evolve-2024-05-23-01-44-fixed.txt)
