### ISSUE TITLE
Achievement "Cult of Personality" not showing in message log

### ISSUE THREAD

**Issue by gnomesurf** [pmotschmann/Evolve#1156]
Upon bioseeding, the achievement appears properly in the achievement list, but does not show as being unlocked in the message log.
Attached are screenshots and saves from before and after.
![cult1](https://github.com/user-attachments/assets/1b3f4652-8276-46bb-b4ef-85ffaea49f01)
![cult2](https://github.com/user-attachments/assets/a00b0d81-480e-414b-ba1c-4431df7c207e)
[evolve-2024-08-06-07-08.txt](https://github.com/user-attachments/files/16510071/evolve-2024-08-06-07-08.txt)
[evolve-2024-08-06-07-10.txt](https://github.com/user-attachments/files/16510072/evolve-2024-08-06-07-10.txt)

**Comment by Raragyay** [comment]
Hmm, it seems like your message log settings are set to only save 3 messages per category upon reload - which might indicate why only the last 3 achievement logs are preserved. When I increase messages saved on reload for achievements (and possibly all, if you would like to see it there as well), I can see all the achievements you get. 
![image](https://github.com/user-attachments/assets/d216805d-f8d6-4675-8607-97cd67e332ea)
![image](https://github.com/user-attachments/assets/2ecf39e2-f3f1-4d02-a123-bced6dc8e44e)

Try this save, for example. All I've done is increase the number of achievement and `All` logs persisted after reload (via settings button next to message log).
[evolve-2024-08-07-00-47-for-github.txt](https://github.com/user-attachments/files/16518346/evolve-2024-08-07-00-47-for-github.txt)
