### ISSUE TITLE
add localization support

### ISSUE THREAD

**Issue by Rodrigodd** [pmotschmann/Evolve#118]
I'm from Brazil and I ended enjoying this game a lot.
So I wanted to add a portuguese translation in the game (more for wanting to make my first contribution to open source), but I realized that all strings are written directly in the code.
It would help a lot if there were only one, or just a few, files that contained all the strings.
And a way the change the languages in run-time, of course.

**Comment by pmotschmann** [comment]
That's going to be a lot of work but if you're willing to translate the strings i'll give some thought to how to modify the game to support it.

**Comment by pmotschmann** [comment]
There is a support mechanism now for this in place on the localization branch. Not all the strings have been abstracted to locale.js yet but it's enough to get an idea on how it will work. There is a lot left to refactor.

**Comment by Rodrigodd** [comment]
Ok. I will start working in the translation, and I do the refactor too.

**Comment by pmotschmann** [comment]
I nearly have events.js complete but I had to go to work so it didn't get committed yet.

**Comment by pmotschmann** [comment]
I've refactored out a bunch of additional strings for translation from races.js and the evolution stage of the game.

**Comment by pmotschmann** [comment]
The game code is 99% refactored; New languages can be added by making a copy of the English strings.json file and then translating it and submitting the new language file in format of strings.locale.jason.
Will close this case once the Portuguese translations courtesy of Rodrigodd is done.
