### ISSUE TITLE
Safety Deposit Box

### ISSUE THREAD

**Issue by OncomingStorm41** [pmotschmann/Evolve#1182]
Withdrawn.

**Comment by OncomingStorm41** [comment]
You will never find a financial institution calling it that. I work for one. Wikipedia is wrong. Which is not a shocker.

Yahoo Mail: Search, Organize, Conquer 
 
  On Sat, Aug 31, 2024 at 12:51 AM, ***@***.***> wrote:   


https://en.wikipedia.org/wiki/Safe_deposit_box


A safe deposit box, also known as a safety deposit box, is an individually secured container, usually held within a larger safe or bank vault.

**Comment by Raragyay** [comment]
I'm hesitant to agree with such a blanket statement. For example, [Scotiabank](https://www.scotiabank.com/ca/en/personal/bank-accounts/account-services/safety-deposit-boxes.html) which is a Schedule I Bank in Canada calls it a safety deposit box.
