### ISSUE TITLE
Bioscience lab and Wardenclyffe are missing from the wiki but show up in search

### ISSUE THREAD

**Issue by DianaNites** [pmotschmann/Evolve#1183]
Both the [bioscience lab](https://pmotschmann.github.io/Evolve/wiki.html#planetary-structures-biolab) and the [wardenclyffe](https://pmotschmann.github.io/Evolve/wiki.html#planetary-structures-wardenclyffe) are missing from the wiki, but both show up in the [search results](https://pmotschmann.github.io/Evolve/wiki.html#search) as supposedly under structures -> planetary.

**Comment by yarukishi** [comment]
Can you post a save file where this happens? I can't reproduce the issue.
