### ISSUE TITLE
Scout the Pit mission not affected by Heavyweight Champ perk

### ISSUE THREAD

**Issue by sylverfyra** [pmotschmann/Evolve#1196]
Fuel costs to every other mission to explore a new area are affected by Heavyweight Champ, but for some reason this one isn't (double checked by comparing wiki cost in an incognito browser window, also 300k/200k)

![image](https://github.com/user-attachments/assets/e5be7a29-641a-462f-a92c-ca7e1d6f8884)

**Comment by pmotschmann** [comment]
Hell is considered to be outside the universe and is not affected by things like this.
