### ISSUE TITLE
Adamantite Jackhammer seems to be bugged 

### ISSUE THREAD

**Issue by TheLobitzz** [pmotschmann/Evolve#1209]
The wiki says that Adamantite Jackhammer increase production for Coal and Uranium, but this doesn't seem to happen when I compared the rates before and after the tech was researched. It seems to apply for Iron and Copper. 
![image](https://github.com/user-attachments/assets/4cadb1e4-f73b-4714-b94b-54b1d76ea23d)

**Comment by yarukishi** [comment]
It seems that pickaxes no longer affect coal or uranium at all, but explosives do. The commit that added Living Tool is associated.

https://github.com/pmotschmann/Evolve/commit/6f8046349a1e1392c8f4a5f22fe1458d59578bc9#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79L5743
