### ISSUE TITLE
BUG: CAN'T earned Achievement "Better dead than red" 

### ISSUE THREAD

**Issue by sslyc** [pmotschmann/Evolve#1213]
Deciding to earn Achievement "Better dead than red", I couldn't  build Spaceport on Mars. That means I couldn't build Garage, which supplies Nano Tube storage. My Nano Tube was always 0, even though I could produce it in factory. When entering Interstellar, I found both Transfer Station and Nexus Station required Adamantite.  Only the Mining Droid could gather it. But the Mining Droid required 75k NanoTube  to Build on the first tap. The only building that supplied NanoTube  storage so far was Warehouse in α Centauri. Each one only +2672 max amount. That was far less than I needed.  Considering, there might be some bugs on this achievement. (Or, I've missed some important Buff or condition?). What if modifying the storage amount of NanoTube  supplied by Warehouse in α Centauri?  I think up to +26720 will fix the problem.

**Comment by johnm0nty** [comment]
Not a bug, you just need more storage bonuses. I was getting 7600 per warehouse when I completed it.

**Comment by sslyc** [comment]
> Not a bug, you just need more storage bonuses. I was getting 7600 per warehouse when I completed it.

Thanks for replying.  I'll try it again in the future.
