### ISSUE TITLE
Gloomy trait not applied to Emocorns

### ISSUE THREAD

**Issue by yarukishi** [pmotschmann/Evolve#1237]
The trait is named "gloomy", but the trait applied after evolution is "broody", so it sort of exists and doesn't do anything.

https://github.com/pmotschmann/Evolve/blob/e87cf274dc2b48673b69adc9e537474204d6ff32/src/actions.js#L7617

It would be good to add some quick save upgrade code along with the fix.

Originally reported on Reddit: https://www.reddit.com/r/EvolveIdle/comments/1gem9wq/emocorn_dont_have_gloomy_trait/

**Comment by pmotschmann** [comment]
Fixed
