### ISSUE TITLE
A.R.P.A. Stock exchange requires plywood with kindling_kindred 

### ISSUE THREAD

**Issue by boisei0** [pmotschmann/Evolve#127]
0.4.7, playing with Ents. Lumber/Plywood is not available because of the racial trait `kindling_kindred`. Has been removed from all costs except for the Stock Exchange. 
Without studying the code in detail I'm not sure why it happens, considering `addProject` has a kindling adjustment in it, and the stock exchange gets added through it.
https://github.com/pmotschmann/Evolve/blob/3bc075fbd32023f2b42628f8d76f1f2cf6268cfa/arpa.js#L69

Image added for clarity:
<img width="833" alt="Screenshot 2019-06-22 at 09 48 27" src="https://user-images.githubusercontent.com/1899092/59961101-f2db1d80-94d2-11e9-994e-919f785b9b3d.png">

**Comment by pmotschmann** [comment]
Do you have a save string with this issue you can upload? I checked it out using an old ENT save of mine but I wasn't being charged any Plywood.

**Comment by boisei0** [comment]
Sorry, no I don't. Usually I make an export just before I reset, but this time I forgot to do that. Hmmm should have thought of that. I started the run during 0.4.5, saw it was present when I got the Stock Exchange research bought, checked the changelog and refreshed to 0.4.7, and saw it was still present there. But beyond that I'm afraid I'm not having more information :/

**Comment by pmotschmann** [comment]
Couldn't replicate issue.
