### ISSUE TITLE
Add research/building cost timer

### ISSUE THREAD

**Issue by nivensd** [pmotschmann/Evolve#130]
It would be nice if the cost pop-ups for buildings, researches, etc showed how long until you have enough of a resource to buy it. Much like how hovering over a resource shows how long until it's maxed out.

**Comment by Colton-Bell** [comment]
Additional, also in the Market tab, when you hover over the "Buy" option, how long it takes till you can purchase at the rate of how much you are earning would be cool.

**Comment by pmotschmann** [comment]
Added by 440b19eae662acaedee3aae7fd8245eff85bde2b
