### ISSUE TITLE
Launch Facility remains after 100% allowing for multiple levels. No description of benefits.

### ISSUE THREAD

**Issue by oxideseven** [pmotschmann/Evolve#131]
After the Launch facility is fully built, it used to disappear. It remains in ARPA now and can be invested into. The description doesn't say it does anything however.

**Comment by oxideseven** [comment]
I got it to level 4, I then posted this, and then it disappeared... Might not be a real problem?

**Comment by pmotschmann** [comment]
well it should have disappeared after the first one, the extra's do nothing.
