### ISSUE TITLE
Suggestion: Group buildings on the village tab

### ISSUE THREAD

**Issue by pmoeller91** [pmotschmann/Evolve#139]
Right now, buildings on the village tab are a mess, especially once you get to a point in the game where there are many different buildings available to purchase. I would suggest adding categories similar to those employed in the space tab to better differentiate the different categories of building (Housing, military, research, ...).

**Comment by pmotschmann** [comment]
Was added in 64ea6922e51785767d9547c6e64ccb88931810c8
