### ISSUE TITLE
Suggestion: Add visual styling to resources panel to improve readability

### ISSUE THREAD

**Issue by pmoeller91** [pmotschmann/Evolve#140]
With the way resources are styled right now, it can be pretty easy to lose track when trying to go from the resource name to the resource quantity and production amounts, especially on a higher resolution. 
I suggest adding alternating row shading to the resources (similar to the market tab) and maybe borders between the different resources, to allow for easier viewing and less visual confusion.

**Comment by pmotschmann** [comment]
Resolved by d6d36c093309b931d987b475a9969f1490d1d4b2
