### ISSUE TITLE
Display somewhere how long a cycle is

### ISSUE THREAD

**Issue by blindley** [pmotschmann/Evolve#142]
All the resource gains and losses in the game are calculated on a per second basis. Except for crafted goods. I understand this is because the crafted goods don't come by the second but by the "cycle", which is a month by default but can be improved with upgrades.

But there doesn't seem to be any information presented about how long (in seconds) a month or a cycle is, so I have to manually time it. It would be nice to have that information available so I could use it to calculate how many materials per second my crafting will use, since that number is not applied in the resources display.

Better yet, do the calculation for me. For example, in the tool tip for Plywood, where it says "-150 Lumber/cycle", you could put in parenthesis next to that how much Lumber per second it is.

**Comment by gmlz** [comment]
I agree. Cycles are confusing and more information / right information must be shown.

**Comment by pmotschmann** [comment]
Resolved by 407b3efab9e658b0ba97b1acb67c494b399eba4e
