### ISSUE TITLE
Low Priority Suggestion: New Achievement - Minarchist

### ISSUE THREAD

**Issue by hotshot21983** [pmotschmann/Evolve#146]
After activating "Corrupt Politicians", and user sets taxes to 0%, the "Minarchist" achievement is gained.

Text can be like 
"Doing away with both parties in a two party system"

Ping r/Libertarian for more text ideas, I'm sure the community will give a long list.

**Comment by pmotschmann** [comment]
Interesting for flavor, but I think it would need more depth then that as just setting your taxes to 0% seems way too easy for an achievement unlock.
