### ISSUE TITLE
Taxes jump to max when first increased

### ISSUE THREAD

**Issue by pmotschmann** [pmotschmann/Evolve#150]
clicking the arrow to increase tax for the first time in a run raises it to maximum instead of by 1

**Comment by danielsan901998** [comment]
`if (!global.civic['taxes']){
        global.civic['taxes'] = {
            tax_rate: '20',
            display: false
        };
    }`
tax_rate is a string
` else if (global.civic.taxes.tax_rate < 30){
                    global.civic.taxes.tax_rate += inc;
                    if (global.civic.taxes.tax_rate > 30){
                        global.civic.taxes.tax_rate = 30;
                    }
                }`
When you add inc instead of 21 the result is 201 and when compared with 30 the result is true, then is set to the maximum value

**Comment by pmotschmann** [comment]
Resolved by 040912759a39576ad3fbdd599371e9180fc75e29
