### ISSUE TITLE
Unemployed civics dissappearing and not returning

### ISSUE THREAD

**Issue by jkilian15** [pmotschmann/Evolve#153]
Since 0.5.0 if I take people off jobs and onto unemployment, they dissappear at a rate of about 1 or 2 per second but the total civics remain unchanged. Right now it shows humans 204/204 however I only have 182 available to employ. I don't think they are returning but I will stay away from moving civics to unemployment and see if they are born again

**Comment by pmotschmann** [comment]
Fixed by f9987767973f2a20f5f34fc7f5d34788ee471b91
