### ISSUE TITLE
it is a bug of the research queue

### ISSUE THREAD

**Issue by lazy0327** [pmotschmann/Evolve#158]
It is a bug of the research queue, for it did not judge whether a certain technology had been studied before the queue study it automatically, which will cause building level clear in some condition.

You can reproduce this bug by doing the following, when there is a technology in the research queue and the queue has not been automatically studied, manually study it and the technology won't be removed from the queue, but the technology has been studied indeed, so the tech will be re-studied automatically, which may lead to repeated studies of some unlock-building technology, then the corresponding building level will be cleared.

![1](https://user-images.githubusercontent.com/37991438/63663397-c99d7d00-c7f4-11e9-856b-324b0f6ae72e.png)

![2](https://user-images.githubusercontent.com/37991438/63663396-c904e680-c7f4-11e9-83b1-82fb353e6f8d.png)

![3](https://user-images.githubusercontent.com/37991438/63663395-c904e680-c7f4-11e9-8b45-332bba7d5ac1.png)

![4](https://user-images.githubusercontent.com/37991438/63663394-c904e680-c7f4-11e9-8e4b-834acefa0d5b.png)

![5](https://user-images.githubusercontent.com/37991438/63663393-c86c5000-c7f4-11e9-926b-65501d4ff45d.png)

**Comment by pmotschmann** [comment]
This was fixed by 3535b69cc7991db88d5c6831e425de42b37a4b8f
