### ISSUE TITLE
"Clear log" button

### ISSUE THREAD

**Issue by gmlz** [pmotschmann/Evolve#164]
Many users prefer to clear log entries after they've been read, and have no further purpose. This is similar to deleting mail after reading it if it has no further purpose.

**Alternatively**, there could be a "Hide all" button that trades out with a "Show all" button. When anything gets logged, it will show. So "Hide all" is akin to "Mark all as read" and equates "read"="archived". Only unread/unarchived text is shown. When everything is marked as read / archived, then the "Show all" button appears, which will flip everything to a shown / unread / unarchived state. This is more complicated than the original idea, but it would protect the history, if that's a design objective.

**Comment by isaiahfisher** [comment]
@pmotschmann I am trying to implement this enhancement via pull request. I am finding it difficult to determine where to place my button. I want to maintain proper style of the game and also maintain programming standards. Could you advise me on where you would like me to place the button?

**Comment by pmotschmann** [comment]
If I were going to add advanced log options they would probably go here
![image](https://user-images.githubusercontent.com/1706210/104644957-78f22280-567c-11eb-8959-1c72868d2956.png)

**Comment by isaiahfisher** [comment]
Ok sounds good. I hate to be a bother, but do you know where in the code that would be? I am pretty new to the template style and I want to make sure I keep up your organization structure. I have the function to do the log clearing finished I just need to know where to drop the button in the code.

**Comment by pmotschmann** [comment]
The message log is currently just a div with the id msgQueue which is defined in index.js (line 695), it's appended to by the messageQueue function in functions.js. The game doesn't really have a proper MVC system if that's what you were hoping to see. The log is pretty basic atm. On loading the game the 3 most recent log messages are re-rendered by main.js at line 90-93.

I would make the clear button call `clearElement($('#msgQueue '));` which is function in functions.js (already imported in most other modules) used to clear various elements. It handles garbage collection of vuejs objects to prevent memory leaks. The message log doesn't actually have any vue objects in it currently but I prefer to keep all removals run through this common function rather then allowing any function to call .empty() or .remove()

**Comment by isaiahfisher** [comment]
ok! Will do. I just wanted to make sure I would not be ruining any standard system. I will add the button.

**Comment by pmotschmann** [comment]
I'd also test this with a small window size, the queue swaps to the left column if you shrink the window and it doesn't have as much space available. it might be best to only show this option if the log is on the right side because of limited UI space.

**Comment by isaiahfisher** [comment]
I think my knowledge of Vue is not strong enough to finish this task unfortunately. I am stuck with connecting the clearElement function to the button. I am not sure how to get the build to recognize the function.
