### ISSUE TITLE
Allow re-ordering queue

### ISSUE THREAD

**Issue by gmlz** [pmotschmann/Evolve#178]
* If the item is first in the queue, clicking it removes it from the queue.
* If the item is anywhere else in the queue, clicking it bumps it to the front of the queue.

Why is this better? Because the most common action the user wants to perform on the queue is to re-order, not remove.

**Comment by Theo47** [comment]
Personally i find the more common action to be removing items rather than wanting to bump them specifically to first place and i feel that this change would make removing items annoying.
