### ISSUE TITLE
Possible Rainbow Issue

### ISSUE THREAD

**Issue by HLXII** [pmotschmann/Evolve#186]
https://github.com/pmotschmann/Evolve/blob/6b3d2b6cc1ff64331036fc6da0bf2c5e98d582d1/main.js#L460

https://github.com/pmotschmann/Evolve/blob/6b3d2b6cc1ff64331036fc6da0bf2c5e98d582d1/main.js#L4139

Currently `global.race['rainbow']` is always 1 or 10~20, which means the rainbow bonus is always active. Or I don't know how the weather system works.

**Comment by pmotschmann** [comment]
It's an unfinished unicorn trait. you need the rainbow ability in the first place or it can't activate.
