### ISSUE TITLE
Not translated

### ISSUE THREAD

**Issue by DimplyKhan13** [pmotschmann/Evolve#196]
In Portuguese, the string "You are protoplasm in the primordial ooze", is not translated.
I could not find these in the pt_br file.

*Found under Race, in the early game.

**Comment by Rodrigodd** [comment]
This is translated. But the messages already sent is not translated when the language is changed. So you never will see this message translated in the first time.

I think this need be fixed

**Comment by pmotschmann** [comment]
Old messages can't be translated because of how it's stored. They will forever be in whatever language it was in when the message was sent to the message queue.,
