### ISSUE TITLE
"Fortifications" on hellscape planet

### ISSUE THREAD

**Issue by pravi-samaratunga** [pmotschmann/Evolve#215]
The text for the research upgrade for "Fortify Hell" on hellscape planets doesn't reflect that they're fighting angels. Instead, it still says that they're fighting demons, which doesn't really fit the theme of the hellscape planet.

**Comment by pmotschmann** [comment]
They are not fighting angels in the hell dimension.
See Blood War achievement.

**Comment by pravi-samaratunga** [comment]
In that case, the following is misleading:

`"event_doom_alt": "A portal to heaven was accidentally opened on %0, a lone space marine wearing green armor somehow managed to stop the angelic invasion."`

This is why I thought it was an angelic invasion, and I missed the text of Blood War.
