### ISSUE TITLE
Cannot unlock tech_steel when using race_seraph

### ISSUE THREAD

**Issue by gjy1992** [pmotschmann/Evolve#224]
The race_seraph has no solders but peacekeepers, which made launching a campaign impossible. So there is no way to get steel resources. However, unlocking the steel technology needs 25 units of steel.

**Comment by Rodrigodd** [comment]
You can't buy steel?

**Comment by Theo47** [comment]
Apart from combat, there is also a low chance to unlock steel via trade routes.

**Comment by gjy1992** [comment]
@Theo47 Yep, the chance is really low...(╥╯^╰╥)

**Comment by Theo47** [comment]
> 
> 
> @Theo47 Yep, the chance is really low...(╥╯^╰╥)

The check triggers quite often though so the overall chance to unlock it feels good.

Some pointers:

- It only triggers from trade routes and not buying resources manually.
- It triggers from active trade routes regardless on whether it is set on buying or selling goods.
- It counts resources with active trade routes and not number of routes so it has the same chance to trigger regardless of if you e.g put 1 or 100 routes on lumber.

So for best results, put a trade route on each resource you have unlocked. You can put the route to sell resources if you can't afford to buy them.

You'll unlock steel quit quickly.
