### ISSUE TITLE
Purchasing a powered building with fractional remaining power causes the new building to turn on and bring you negative

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#237]
In an Antimatter universe, for example, each Coal Powerplant I have provides 5.1 kW.  If I turn on 5 Mines for 5 kW, I'm left with 0.1.  Purchasing a new Mine will turn that new one on, bringing me to -0.9kW.  This doesn't happen with whole amounts of kW.

**Comment by pmotschmann** [comment]
Resolved by acdc340ee9ccf3c2e920e1198436d75a60b74542
