### ISSUE TITLE
Last Rites is marked as unbuyable

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#239]
![image](https://user-images.githubusercontent.com/7085132/68399243-1cc07400-0144-11ea-93af-e5ba2d4627f4.png)

In this screenshot, Iron Axe (which requires 2700 knowledge) is buyable (as my knowledge cap is ~3000), but Last Rites (which claims to require 1000 knowledge) is not listed as buyable.  This does not prevent buying it.

**Comment by boozledorf** [comment]
As an aside, Last Rites is only viewable after a refresh once Sacrificial Altar is purchased.

**Comment by nivensd** [comment]
I just tried to queue Last Rites (even though it was shown as not buyable) and it disappeared. Has yet to show again, even after a couple refreshes. It also doesn't show in the Completed research section.

**Comment by pmotschmann** [comment]
Fixed in 3b0456f8c907c2d530ddc989408791c5daf1ed14
