### ISSUE TITLE
Spy Executed by wrong foreign power

### ISSUE THREAD

**Issue by drissical** [pmotschmann/Evolve#251]
I see 3 different foreign powers, not sure if that is how it always is, i have not dont a reset on this update.  I created a spy for each one then sent an influence spy at the second and third power ignoring the first one.  The message I got back a bit later said the second foreign power one completed and the first foreign power killed my spy. The issue is I did not send one to that place and i never got a message about the third.

As an example to what I am thinking imagine one array is keyed as 1,2,3 and the other is 0,1,2  something simple like that, not sure how it is setup but that is what it reminds me of.

**Comment by pmotschmann** [comment]
Fixed by c0b84811758b9503ee3473efab9119ec6b94d3c6
