### ISSUE TITLE
Antimatter energy bug

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#253]
Elerium Reactor doesn't provide any extra energy in AM universe:
![image](https://user-images.githubusercontent.com/7085132/69484122-78098c00-0dfd-11ea-87cf-d9229ca7d8e2.png)
![image](https://user-images.githubusercontent.com/7085132/69484123-7d66d680-0dfd-11ea-9792-0f9672d5a8ec.png)

Also, Geothermal Plant didn't show any extra energy at the start of my run on the rollover display (but did in the energy breakdown), but that seems to have been fixed.

**Comment by pmotschmann** [comment]
Resolved by c0b84811758b9503ee3473efab9119ec6b94d3c6
