### ISSUE TITLE
Uranium tooltip broken

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#259]
![image](https://user-images.githubusercontent.com/7085132/70288540-fc65f280-179f-11ea-9ba3-801a2412041e.png)

**Comment by pmotschmann** [comment]
issue is unclear, I've observed no issues with the uranium tooltip.

**Comment by boozledorf** [comment]
It appears to have been some glitch with the run I was on.

https://pastebin.com/DYvVse9m Here is a paste of the save I was using when I noticed it, in case you're interested in looking into this further.  Resetting seems to have cleared it up.

**Comment by pmotschmann** [comment]
weird, issue reopened.
