### ISSUE TITLE
Unable to add buildings to queue when ARPA projects are in the queue

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#260]
![image](https://user-images.githubusercontent.com/7085132/70298943-693db480-17c1-11ea-86e9-690294a0420c.png)
I am not able to add a Wardenclyffe to this queue, but I can clear every item, add the Wardenclyffe, and _then_ add the two ARPA projects after it.

**Comment by JaapvdG** [comment]
I have the same issue. Can add items, but only if no ARPA projects in the queue. I can always add ARPA projects, even if there already are ARPA projects in the queue

**Comment by pmotschmann** [comment]
Resolved by 4f0de4cdc5dfb13681ba6f6d9d87ae7ee00e9a89
