### ISSUE TITLE
Phoenix MAD

### ISSUE THREAD

**Issue by jfalardeau** [pmotschmann/Evolve#270]
I just did a phoenix run, 4 stars with MAD reset.
No achievement, nor mastery was given.

**Comment by pmotschmann** [comment]
Where you in a micro universe?

**Comment by jfalardeau** [comment]
Standard universe. I only got a save of a Salamander run I did right before the Phoenix, is it enough for you?

**Comment by pmotschmann** [comment]
Unfortunately if it's not from the Phoenix run then it's probably not going to reveal anything useful.

**Comment by pmotschmann** [comment]
CNR
