### ISSUE TITLE
Graphene production bug?

### ISSUE THREAD

**Issue by BartMassey** [pmotschmann/Evolve#274]
First off, thanks huge for Evolve: it's a fantastic fun game. I'm really enjoying it.

I've found something that's either a bug or a misunderstanding on my part. When I look at my Graphene production I see this:

![graphene](https://user-images.githubusercontent.com/117151/71406264-7b568a00-25ec-11ea-85b2-b4bb18bbf08e.png)

I have 6 Graphene plants running, and it seems like my morale bonus of 61% alone should push that up to 9.66 units / sec of output: with the other bonuses (61% morale + 8.55% plasmids + 25% conquest = 94.5%) I feel like I should be seeing 11.67 units / sec. This assumes no stacking: otherwise the output should be 6 * 1.61 * 1.0855 * 1.25 = 13.11+. As you can see I am currently only experiencing 7.86 units / sec.

If I compare the situation with Titanium, I see the stacked version of bonuses in full effect:

![titanium](https://user-images.githubusercontent.com/117151/71406974-90ccb380-25ee-11ea-8bf4-f14f391ccb46.png)

4.67 * 1.61 * 1.0855 * 1.25 = 10.202, which is close enough to 10.19 to be rounding error.

Help me out here: I'm 20% done with the Stellar Engine on my first run, and only mass Graphene production stands in the way of quick completion. :grin:

**Comment by BartMassey** [comment]
Just found this Reddit thread: https://www.reddit.com/r/EvolveIdle/comments/dqncfo/graphene_bugged/

Sure enough, if I account for 0.6 Graphene / sec / plant I get the in-game number. So I guess it's just a tooltip bug. Would be nice to fix, and also to document somewhere in-game that Graphene plants produce 0.6 units / sec.

**Comment by Beorseder** [comment]
This has been resolved.

**Comment by BartMassey** [comment]
Thank you!
