### ISSUE TITLE
Better descriptions of ARPA projects

### ISSUE THREAD

**Issue by Katorone** [pmotschmann/Evolve#276]
The ARPA projects claim to help with various gameplay elements, but it's unclear if they really do, or to which extend.  This leaves me with questions like: "Is it worth building 10 libraries, or should I invest in the Supercollider instead?".

Could you add more context/explanation to what the benefits of these projects actually are, please?

**Comment by Beorseder** [comment]
After constructing a level of one of an ARPA project, you can hover over the "Level - #" that appears and see the exact effects that they provide.

**Comment by Katorone** [comment]
Right, but that's after a huge investment.  Maybe adding a "Level - 0" with the description would be an option?

**Comment by Beorseder** [comment]
Well, they're not really that large of an investment compared to how much more content there is afterwards and how many times you are likely to play through the game.

**Comment by Katorone** [comment]
That's a fair point, though at the point I'm at, they'd take 3d to complete when idle, which I think is a considerable investment.  I'm coming at this as a new player, having only played a few days so far.  I like to plan ahead a bit, the ARPA projects-tab was the first, so far, that left me stumped on what it actually did.  Seeing how Genetics & Crispr seem to be prestige related, I considered maybe the projects were as well.
