### ISSUE TITLE
Observation: It's strange that queued builds are logged, but immediate builds aren't

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#278]
Queue a long build (maybe a bank)

Then immediately build something (maybe a trade post)

Now engage in some war to pay for the bank

Log shows "built a bank" but not "built a trade post"

That's peculiar 😄

**Comment by pmotschmann** [comment]
Was the trade post actually queued? They only show in the log if it was on the queue.

**Comment by StoneCypher** [comment]
yeah that's my point.  they only show in the log if it was on the queue.  that's weird.

**Comment by pmotschmann** [comment]
That was intentional. The queue ones announce it was constructed so you can see in the log what finished while you were away. Making every thing you manually build add to the log would spam it with information that wasn't considered important since you aught to know what you just built.
