### ISSUE TITLE
Are you open to CSS pull requests?

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#279]
I'd like to fix #269, and a few other things like it

**Comment by pmotschmann** [comment]
Duplicate of #269 please contain discussion to a single thread

**Comment by StoneCypher** [comment]
well, i also meant stuff like "could i donate a theme" and whatever

**Comment by StoneCypher** [comment]
i guess i might have, y'know, said that

**Comment by pmotschmann** [comment]
Absolutely you can. The current themes are all defined in src/evolve.less. I tried to keep the theming aspects of it separated from the rest of the styling code near the bottom. You can use an existing theme as a base this way or just start fresh.
