### ISSUE TITLE
Tried to build.  Nope

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#283]
I wanted to start making a theme, so I set your stuff up

I think I'm doing something pretty profoundly incorrectly.  Building with webpack produces some stuff in dist, but hosting the repo root means it's loading the string "source/whatever" instead of the actual script

Neither building in dev nor production seems to yield a webserver

So I made a directory, copied the build residues, html, strings, lib, and fonts in there, hosted that, but now the bundle seems to be trying to load `evolve.js` from the server

So I manually built evolve.js but that appears to just be producing main again this time at 1/3 the size, so I assume it's actually part of the main bundle and the main bundle just doesn't know that for some reason?

I don't seem to know how to start this software locally.  Sorry for such a noob question

**Comment by pmotschmann** [comment]
Building the webpack just compiles the game bundle, it doesn't launch a webserver.
I use simple http server, which if you are using Linux is just "python -m SimpleHTTPServer" (run from the repo root) and then you can load "http://127.1.1.0:8000" from any browser to test the game. 

If you are working on a theme though you need to recompile the CSS file which is done with the command "npm run less". Rebuilding the webpack bundle doesn't rebuild the CSS file.

Rebuilding the webpack can be done with "npm run build" for production or "npm run dev" for debugging.

**Comment by StoneCypher** [comment]
Yeah, so, I had tried to tool this.  I got most of the way there, but, it keeps trying to load `evolve.js` and I can neither satisfy that nor convince it that it's part of the build

https://github.com/StoneCypher/Evolve/tree/AddServeHereForDev

**Comment by StoneCypher** [comment]
I really thought [line 11 here](https://github.com/StoneCypher/Evolve/blob/AddServeHereForDev/package.json#L11) was what it wanted, but that builds a new `main.js` instead that doesn't run

so I feel like maybe it's just failing to build into the bundle somehow?  i dunno.  i am a rollup person, rather than a webpack person

**Comment by pmotschmann** [comment]
The entry point is not evolve.js, it's main.js.

There is no need to add new script definitions to the package.json file. The existing ones are the correct ones. Don't try to define your own, use the already working one. If it's not building then you probably have something wrong with your npm installation.

You should just be able to `git clone https://github.com/pmotschmann/Evolve` or in your case your own fork, then launch a webserver with `python -m SimpleHTTPServer` (run from the repo root) and the game can then be accessed from localhost (by default it will be on port 8000). If you are not able to run `npm run build` without issue then there is likely something wrong with your environment.

I run a Linux environment for development, if you're trying to do this on Windows then that might be causing your problems. I'm not sure how to resolve them in that case other then suggest you install the Windows Subsystem for Linux (Assuming you have Windows 10) and use an Ubuntu installation for your CLI.

**Comment by pmotschmann** [comment]
I suggest joining the discord and asking in the scripting channel for additional help.

**Comment by StoneCypher** [comment]
So, found the bug.

Those files in root pointing at the real things are symlinks.  This will also fail on older macs, under Centos, on Arch, et cetera

It's kinda weird to point a web resource at a symlink, and also (not that it'll happen in a dev environment) generally considered a pretty serious security hole, since it's not unreasonable that that file gets written to from within a jail that'd exclude exterior writes, but be able to get out since it has a symlink bit

I guess I'll just manually make the symlink, but most node projects would treat this as a bug, and change the html to point at `/dist/main.js` instead

Normally I'd submit a patch to do that but you told me not to mess with your build
