### ISSUE TITLE
Sabotaged so much they are back to the start

### ISSUE THREAD

**Issue by tombomb** [pmotschmann/Evolve#286]
I don't know how to word the title, but i have sabotaged the Divine Federation so much that they are back to a weak military of 50.  Every time i try to lower them, the log says it goes down but it stays at 50

**Comment by tombomb** [comment]
Just found out that Foreign names are random, its the first foreign power for me and here is my save 
https://gist.github.com/tombomb/35bf5413ea2311b0301bacbac07711ea

**Comment by pmotschmann** [comment]
Resolved by db83a7fbea9ea2779ba2306c5ae4eebf9fc4ac13
