### ISSUE TITLE
window.evolve.actions action() functions not behaving when called from userscript

### ISSUE THREAD

**Issue by AndreasTPC** [pmotschmann/Evolve#287]
I'm making a script to automate some of the more tedious parts of the game that I feel like I've done enough times manually to not want to have to do again. I'm trying to use the actions provided in window.evolve.actions as they're more convenient than parsing the DOM. However, there are some problems.

For the techs, when you call action() it takes the resources required and returns true but does not actually research the tech.

For the buildings, the action() builds the building as expected, but it does not update the UI. So if there's a new building it'll still look like it has not been built in the UI, even thought it actually has. The problem correct itself after a while, or if you click the building button manually.

**Comment by Beorseder** [comment]
There are already two popular scripts that people use, just in-case you didn't know.

**Comment by AndreasTPC** [comment]
Yeah, thanks, I'm aware. I'm making my own because I want to make sure it's not going to automatically go trough some stage of the game I haven't seen yet. So for example instead of making a script that researches all techs I have a list of techs it can research that I've already seen enough times and it only researches those automatically.

**Comment by pmotschmann** [comment]
I don't provide script support.
