### ISSUE TITLE
Unassigning a worker should assign it to the default, not Unemployed

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#297]
Scenario:
![image](https://user-images.githubusercontent.com/7085132/73100057-cb11c500-3eba-11ea-8ecc-e1faaf1d82b3.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/7085132/73100079-d36a0000-3eba-11ea-8068-3a2b95005ec3.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/7085132/73100092-da910e00-3eba-11ea-9200-ebfd51353e90.png)

**Comment by boozledorf** [comment]
(Removing from the default should assign to unemployed if you truly want unemployed workers)

**Comment by pmotschmann** [comment]
Exists in Intergalactic branch
