### ISSUE TITLE
Enhancement: Show build cost on building queue hover 

### ISSUE THREAD

**Issue by hulkur** [pmotschmann/Evolve#320]
It would be useful if tooltip with build cost would open when hovering on building queue item.

For example when you are on resources screen and want to buy something to speed up building or checking what you need when selling surplus.

**Comment by lxsli** [comment]
An alternative might be to colour the resource names in the main list if a queued item is blocked on it / needs more of it. This would decouple choosing what to buy from optimising production for your queued items somewhat, which has pros and cons. I'd say, more convenient but a bit risky in terms of game immersion.
