### ISSUE TITLE
Whole Game Interface- Color Swap

### ISSUE THREAD

**Issue by FoxyPlayGamer435** [pmotschmann/Evolve#326]
When you start up the game, from what I see, the green colors and the red colors have swapped places. The dollar sign is red, the 'Buy' in the market is Red, losing resources is in green now.
![Annotation 2020-04-01 082739](https://user-images.githubusercontent.com/57278824/78142590-b2f67e80-73f2-11ea-9011-66af60331718.jpg)

**Comment by pmotschmann** [comment]
Check a calendar

**Comment by FoxyPlayGamer435** [comment]
You son of a gun-
