### ISSUE TITLE
Minor bug: spy death text occasionally wrong-colored

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#329]
Spy death event color in dark theme is usually red.  Occasionally it's yellow instead.  No pattern is apparent.

![image](https://user-images.githubusercontent.com/77482/78597649-c34b9680-7802-11ea-9407-94591ed67020.png)

This is not changed on later update.

![image](https://user-images.githubusercontent.com/77482/78597760-f5f58f00-7802-11ea-8882-d054a6ad0be8.png)

**Comment by Beorseder** [comment]
This is not a bug.
Spies can get caught two different ways:
1. From a failed Spy Mission (red text)
2. From a random event (yellow text)

**Comment by StoneCypher** [comment]
oh.  neat.

request slight phrasing difference to make that apparent
