### ISSUE TITLE
French Translation (help needed)

### ISSUE THREAD

**Issue by willoucom** [pmotschmann/Evolve#330]
_This is not an issue._

I think that many French-speaking players might be interested in the game, but do not speak English, as the French are unfortunately generally reluctant to practice foreign languages, even though the young seem to be much better than their elders.

I have started translating Evolve into French and am looking for volunteers to help me.

For french readers:
-----

Je joue à Evolve depuis environ 2 à 3 semaines, je suis actuellement à l'énergie nucléaire et je ferais probablement mon premier reset la semaine prochaine.

J'ai donc commencé la traduction en français, et je recherche de gentils bénévoles pour m'aider dans cette tâche, pour l'instant le code est ici: https://github.com/willoucom/Evolve/blob/french/strings/strings.fr_FR.json

N'hésitez pas à me solliciter si vous voulez apporter votre aide.

**Comment by pmotschmann** [comment]
This doesn't appear to be going anywhere, can reopen if French speaking players become interesting in creating a translation.
