### ISSUE TITLE
resource "full" colour stays even when decreasing

### ISSUE THREAD

**Issue by AI-quote** [pmotschmann/Evolve#335]
<img width="274" alt="Capture" src="https://user-images.githubusercontent.com/28417000/79306431-8b49ff00-7f38-11ea-807a-dd8008740584.PNG">

at my current stage of 7500 food. when decreasing it says it is full. it changes back to white once it gets down to 7400. i upgraded my capacity to 8000 and same thing happens, when it gets down to 7900, it turns back to white.
exact same thing happens when the resource is filling up.

**Comment by Beorseder** [comment]
That's how it works. The color switches to yellow when you're within 1% of the max capacity. It's an indicator that you're close to or at max capacity, so you can react by either using the resource or adding more storage for it.
