### ISSUE TITLE
Bug: Game stopped, civilization system and research tabs empty

### ISSUE THREAD

**Issue by jfalardeau** [pmotschmann/Evolve#348]
All my resources are frozen, the page of the civilization system tab (ex : Gnome System) is now empty, same thing with the two Research tab (New/Completed). 

Game status when it broke : It think it happened just after I unified. I'm using gnomes in the antimatter universe. The last prompt in the game is  "You have purchased Northern Federation". I tried to switch between Firefox and Chrome but the game is broken in both explorer.

**Comment by wdjwxh** [comment]
I just fix that, wait for merge
