### ISSUE TITLE
[bug or intended?]  crafting ratio calculation

### ISSUE THREAD

**Issue by isstwo** [pmotschmann/Evolve#359]
It seems 'ambidextrous' (and 'crafty'?) are calculated twice in crafting ratio. Once in main.js crafting part and once in craftingRatio(res). I'm not sure if this is intedned, or just some lagency coded that is left forgotten.

**Comment by pmotschmann** [comment]
They are working as intended, Auto crafting gets extra benefit from these traits over manual crafting.
