### ISSUE TITLE
Sawmill has no effect and is not displaying.  

### ISSUE THREAD

**Issue by prs9tb** [pmotschmann/Evolve#364]
![image](https://user-images.githubusercontent.com/5963862/83711955-a4933180-a5f2-11ea-8448-05af294fcb9b.png)

**Comment by lxsli** [comment]
![image](https://user-images.githubusercontent.com/88806/86127602-15d1e180-bad8-11ea-8ec9-61c3010e283c.png)

Seems to be working for me, are you sure you don't have a genetic trait or something that's disabling it?

I'm on v0.9.1, maybe it got fixed too.

**Comment by lxsli** [comment]
Wait I had the wrong thing moused over.... confirmed, sorry!

![image](https://user-images.githubusercontent.com/88806/86127824-6c3f2000-bad8-11ea-8f83-099443b37300.png)

**Comment by lxsli** [comment]
sigh I'm not very well... if you buy a sawmill or power one on, you can see a change occurs
