### ISSUE TITLE
BUG: Mining drone appears to have no effect

### ISSUE THREAD

**Issue by hulkur** [pmotschmann/Evolve#366]
Mining outposts 11, output 11*0.04=0.44 as displayed on tooltip
Mining drones 10, not shown

![Screen Shot 2020-06-14 at 14 41 09](https://user-images.githubusercontent.com/11457732/84592299-40236e00-ae4d-11ea-8c5a-d9ddccd91ca7.png)

**Comment by Beorseder** [comment]
It applies to the base output of Mining Outposts.

**Comment by hulkur** [comment]
as per wiki and tooltip, base output is 0.04.
11 Outposts total 11*0.04 = 0.44
Apply all the bonuses, subtract blackhole and you get the number shown for total output.
Droid bonus not found.

**Comment by pmotschmann** [comment]
It's factored into the base value of outposts, you can quite easily see it go up when you buy a droid.

**Comment by hulkur** [comment]
then wiki is incorrect

![Screen Shot 2020-06-15 at 06 35 07](https://user-images.githubusercontent.com/11457732/84615780-8ff84880-aed2-11ea-944e-5bd09396fb1c.png)

**Comment by hulkur** [comment]
Oh, the wiki is changing too ... so where can I see actual base values?
