### ISSUE TITLE
No difference in producing Elerium with one miner ship and two.

### ISSUE THREAD

**Issue by RosieMcCattail** [pmotschmann/Evolve#381]
One Elerium mining ship produces 0.005 E/s. Two ships should produce 0.01 E/s, double that. In practice, the 0.005 E/s production from the first ship is rounded up to 0.01E/s, so adding a second ship makes no difference.
I suppose the same would happen with any combination of neigbouring odd and even numbers, but can't check due to lack of resources for construction.

![3019](https://user-images.githubusercontent.com/43783725/87180494-ed6c9300-c2e0-11ea-8685-e18291303c58.png)
![3020](https://user-images.githubusercontent.com/43783725/87180502-f198b080-c2e0-11ea-8efa-bf14950e5021.png)

**Comment by pmotschmann** [comment]
CNR

**Comment by RosieMcCattail** [comment]
What on Earth is CNR
