### ISSUE TITLE
Idea: double warmonger bonus for autocratic Balorg

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#387]
As it stands, autocracy seems to disable the warmonger bonus for Balorg. This seems counterintuitive and negates a big reason for choosing autocracy. Allowing autocracy to double the bonus instead seems like it would offer approximately the same bonus to Balorg as other races.

**Comment by lxsli** [comment]
As an aside, I almost always go Democracy - Technocracy - Federation. The other bonuses seem weak in comparison. I could easily be mistaken though.

**Comment by pmotschmann** [comment]
Many government types are situational, Theocracy is very strong late game with fully upgrades priests. I preferred Corpocracy for Cataclysm; if you are bottled-necked by manufactured goods such as Nano Tubes Socialist or Corpocracy can win out. Some of these government are not good to run all the time but can be good to run for a while when trying to achieve a specific goal.

**Comment by pmotschmann** [comment]
Addressed in 8e82f2cb029781b1c683cc28f6ff31f39e769171
