### ISSUE TITLE
Occasional hover stick

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#393]
![image](https://user-images.githubusercontent.com/77482/87866507-7619ad80-c937-11ea-986c-573e9791be51.png)

Once in a great while, the storage hover will get stuck over whatever you're over at the time.  During that time, other hovers will appear but their template text will not be honored.  

Re-hovering the storage hover fixes it.

**Comment by pmotschmann** [comment]
No longer relevant
