### ISSUE TITLE
Hover display can be broken

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#395]
Mostly, when you hover a tech in queue, it shows a hover display to explain the tech

![image](https://user-images.githubusercontent.com/77482/88009650-e35c4880-cac7-11ea-99fb-4be60f8a915b.png)

Sometimes specifically reinforced sheds will pop the wrong tech's hover, in the wrong place

![image](https://user-images.githubusercontent.com/77482/88009690-f3742800-cac7-11ea-85de-d4fbc3900b2a.png)

Other times it works as expected?

![image](https://user-images.githubusercontent.com/77482/88009706-fbcc6300-cac7-11ea-811f-6e5aa1aedaff.png)

**Comment by StoneCypher** [comment]
At other times you can get two simultaneously

![image](https://user-images.githubusercontent.com/77482/88010465-c759a680-cac9-11ea-9004-468e83c40bb8.png)

**Comment by StoneCypher** [comment]
hm, it seems like the vertical position of the wrong hover is set by the height of the right panel

**Comment by RosieMcCattail** [comment]
Will add another issue with the hover display.
The item has been in the second position, constructed manually because the resources are being collected from raids at random, _after that_ was deleted from the queue (was showing time as [Never]). Hovering an item over the now second item still shows the old one.
![3042](https://user-images.githubusercontent.com/43783725/88129957-a1bbc280-cbd9-11ea-86d3-4d00a130c72b.png)

**Comment by lxsli** [comment]
Possibly the same issue that Rosie saw

![image](https://user-images.githubusercontent.com/88806/88155311-d5a9de80-cbff-11ea-84ea-4221198826d8.png)

https://gist.github.com/lxsli/bc503ccaf8613a76309e51b7a92e813a

**Comment by lxsli** [comment]
Super easy to recreate in fact. From an empty queue, add two things, say a smelter and a fission reactor (just what I used). Cancel the smelter and check the hover on the reactor, it'll still show the smelter recipe.

**Comment by justino** [comment]
I get the same issue when hovering over crafted materials
![image](https://user-images.githubusercontent.com/224612/90169048-0c40c800-dd6c-11ea-96ea-d9bb499acc1d.png)
![image](https://user-images.githubusercontent.com/224612/90169095-1a8ee400-dd6c-11ea-8199-f1ff8d758a86.png)

**Comment by pmotschmann** [comment]
no longer an issue
