### ISSUE TITLE
Bug: Mantis researches don't affect tooltip

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#398]
I'm playing as Imps and I just Deified Ancients to pick up the Mantis cannibalize ability. The tooltip shows each buff as 15% and this doesn't go up after doing the related researches (Last Rites, Ancient Infusion).

I also can't see the buff in the production breakdown for Iron or Copper, and jobs have no breakdown, so tbh I don't know if the buff is applying at all.

As an aside, it seems weird that I'm allowed to stack the buffs infinitely. If you start as Mantid, you can stack it up very high, very quickly and not need to sacrifice again.

(fwiw I was hoping for hivemind, oops)

**Comment by pmotschmann** [comment]
working as intended
