### ISSUE TITLE
How do you stack bonuses?

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#400]
It is really starting to itch my brain that I don't know how accumulation works.  That said, I'm also too lazy to write down the numbers and figure it out.

If I have five 5% bonuses, is my bonus 25%, or 1.05⁵, please?

**Comment by lxsli** [comment]
Check out https://github.com/pmotschmann/Evolve/blob/c2270b2614c62282b7d68c086f9f7b82974c7d2c/main.js#L447
and https://github.com/pmotschmann/Evolve/blob/c2270b2614c62282b7d68c086f9f7b82974c7d2c/jobs.js
Some familiarity with JS would help but it's not rocket surgery either.

**Comment by pmotschmann** [comment]
This is something that would be better asked on Reddit or Discord

**Comment by StoneCypher** [comment]
yeah, having seen that, it's officially time to contribute
