### ISSUE TITLE
Can't import on master

### ISSUE THREAD

**Issue by StoneCypher** [pmotschmann/Evolve#406]
So I'm trying to set up a new dev environment, and I contributed #404 and #405 from it

The thing is, I went to test #405, and ... I couldn't import a game.

![image](https://user-images.githubusercontent.com/77482/88628373-b927ff00-d062-11ea-9787-d437faa01b9d.png)

This is weird - I can import them just fine in public, and I'm on your code using your build system

Weirder still, this is the problem line, 191:

![image](https://user-images.githubusercontent.com/77482/88628440-d3fa7380-d062-11ea-84da-4e967f4ee9db.png)

That `global` appears to be the one defined in `vars.js`, which ... is not a `const` at all, but rather a `var`.

![image](https://user-images.githubusercontent.com/77482/88628527-f68c8c80-d062-11ea-852b-2c0a9724a884.png)

And like.  I ***think*** I remember there being weird shenanigans about exporting top-level variables for assignment under webpack, because it's Michael Jacksonscript, but I'm very not confident of that.

**Comment by StoneCypher** [comment]
ya actually static analysis confirms

![image](https://user-images.githubusercontent.com/77482/88752200-2e044300-d10e-11ea-95fb-91a46244f8ac.png)

**Comment by pmotschmann** [comment]
Resolved by c8feaf30ad1acdeaf88a3d18ec99feaa81fc9f5c
