### ISSUE TITLE
Bug, quantum level calculate wrong for synthetic fur

### ISSUE THREAD

**Issue by Usernm0** [pmotschmann/Evolve#411]
Furs (665% only):
![](https://i.imgur.com/zFecyjt.png)

Alloy (and any other 2663%):
![](https://i.imgur.com/wGbPelM.png)

Savefile:
[https://pastebin.com/wBSqdqD9](https://pastebin.com/wBSqdqD9)

**Comment by pmotschmann** [comment]
Not a bug
