### ISSUE TITLE
Inconsistent protoplasm stage speed based on previous reset tier

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#412]
I've noticed that there's a noticeable difference in speed in the protoplasm stage based on how you reset.  When I reset via MAD, I have a higher speed of RNA generation than when I reset via Bioseed.

Examples:
[Pre-bioseed reset](https://pastebin.com/qbS8tEaK).  This is a save just before a bioseed.  You can run a bioseed reset, then buy the following items to check the RNA generation speed:
![image](https://user-images.githubusercontent.com/7085132/89296443-58835e00-d630-11ea-9594-94ec10d018f4.png)

[Pre-MAD reset](https://pastebin.com/M8eZjhjL).  This is a save just before a MAD (which was the one immediately following the above bioseed).  You can run a MAD reset, then buy the same items to check the RNA generation speed:
![image](https://user-images.githubusercontent.com/7085132/89296609-908aa100-d630-11ea-8b9a-e33f86620944.png)

I've noticed this for a while, consistently across all universes.  I'm not even sure if this is a bug or if this is an intended feature, but it struck me as odd, so I wanted to point it out.  You can see the only real difference between the two screenshots is the amount of anti-plasmids I have, but if I were to do another bioseed after the second save, I'd see the same issue.

**Comment by pmotschmann** [comment]
This is intentional, MAD adds an effect called Rapid Mutation that doubles RNA gains from Organelles.
