### ISSUE TITLE
Bug: Build queue tooltips persist removal

### ISSUE THREAD

**Issue by Tro2y** [pmotschmann/Evolve#441]
Repro steps:
1. Add three different structures to the build queue
2. Remove the second entry in the build queue
3. Mouse-over the second (previously third) structure in the build queue - Tooltip still shows resource requirements for the removed entry

Page refresh solves the issue.

**Comment by clapointe** [comment]
Reordering the items in the queue also solves the issue, even if you just drag one item around and drop it at the same place it already was.
