### ISSUE TITLE
Display Bug: Left Column (is-one-quarter)

### ISSUE THREAD

**Issue by N-Plus-Plus** [pmotschmann/Evolve#445]
The left-most column doesn't quite fit content (money, power and large capacity resources) without wrapping when half-width on UHD screen, which then jitters up and down as non-fixed-width font numbers change... if class "is-one-quarter" had a min-width of 20rem rather than 18rem, this issue is solved (I do this manually after each load/refresh and it works great)

**Comment by N-Plus-Plus** [comment]
Some update along the way has made this a non-issue on half-UHD resolution. Now redundant, so closing.

**Comment by Abastro** [comment]
I am experiencing this exact bug. Is there corresponding new open issue?
