### ISSUE TITLE
Bug: Unemployed Surveyors

### ISSUE THREAD

**Issue by Tro2y** [pmotschmann/Evolve#446]
When Surveyors die, their replacement pop who are waiting for a Carport to become ready are classed as Unemployed rather than following the default job and bolstering that role while they wait.

This is a minor issue, but leads to a regular Unemployed morale debuff unless frequently manually assigning the unemployed while they wait for a Carport.

**Comment by lxsli** [comment]
This is annoying but I wasn't sure if it was by design. My solution is to build a couple of extra carports and not assign surveyors.
