### ISSUE TITLE
Knowledge Breakdown inaccurate

### ISSUE THREAD

**Issue by pmotschmann** [pmotschmann/Evolve#45]
The Knowledge breakdown seems to be inaccurate. Either this is reporting something wrong or actual Knowledge gain is lower then intended.

**Comment by CapnCrinklepants** [comment]
Still getting some weird totals on knowledge. Working on it now. Here's what I get for knowledge on my debug file. It's a similar large gap on my main game

![image](https://user-images.githubusercontent.com/474882/57388108-67990900-716c-11e9-93d4-305d8ebc2dd4.png)
