### ISSUE TITLE
Bug: Government tooltip stays open after selecting a government type

### ISSUE THREAD

**Issue by clapointe** [pmotschmann/Evolve#451]
Sadly I don't have a screenshot, as I've reloaded the page which solved the problem, but here's what happened: I had the oligarchy government type, and switched to republic. Upon clicking Republic, everything worked normally except the tooltip stayed open, and reloading was the only way I found to clear it. 
This doesn't happen every time, either, so I'm not sure exactly what makes it happen. It's not super annoying, just forces to refresh the page when it happens.

**Comment by alexvy86** [comment]
I've seen this several times too. I thought it always happened after hovering over the current government and then clicking Start Revolution, but I can't reproduce it right now. Next time I see it I can screenshot it.

**Comment by pmotschmann** [comment]
this was fixed
