### ISSUE TITLE
Bug: 10th Space Station won't enable

### ISSUE THREAD

**Issue by Tro2y** [pmotschmann/Evolve#452]
Game state as attached
[Space Station.txt](https://github.com/pmotschmann/Evolve/files/5286139/Space.Station.txt)
. Built a tenth Space Station, didn't affect the building cap when toggled, through the totals below 10 all work as normal... Building an eleventh (to test) does increase the cap as though I'd just built my tenth. Weird.

**Comment by pmotschmann** [comment]
Assign space miners to it.
