### ISSUE TITLE
enhancement idea: Use Crowdin to help manage i18n/L10n process

### ISSUE THREAD

**Issue by RiverCrimea** [pmotschmann/Evolve#458]
The **Contributing a Language file** section of `README.md` begins with:
> If you are interested in a contributing a new language for Evolve the process is fairly straight forward (although a bit tedious).

What if the process were even more straightforward and it weren't tedious at all?

[Crowdin](https://www.crowdin.com/) is designed to do exactly that. Benefits of using Crowdin include:
- Source text is entered one time and updated automatically.
- When source text changes, translators are automatically notified, whether the change is 150 new strings or 3 little typos.
- Requires _no changes_ to the existing code (apart from eliminating the `.py` files currently used for this purpose).
- Translators never touch the JSON files, eliminating formatting errors.
- Ensures tokens remain intact.
- Automatically creates and formats JSON files for each language
- Keeps strings in the same order across languages.
- Does not create keys for untranslated strings, making updates cleaner.
- Pushes translated files to GitHub and creates a pull request.
- **_Does everything for FREE for open-source projects._**
...and many more. In short, it makes every part of the translation process easier.

I have experience setting up and managing the L10n process for open-source projects, and I'm willing to do the same for Evolve. All I require to begin is approval from the lead dev. With that, I can set up everything without interfering with the current process. Once it's set up, the dev can test drive it and make decisions from there.

PLEASE feel free to ask ANY questions you may have. 😺

**Comment by seeker-Liu** [comment]
+1. I noticed many bad translations in Chinese l10n, now fix them will be a pain.

**Comment by Rodrigodd** [comment]
I also +1. I created a lot of python code to take advantage of some of these benefits for my pt-BR translation (tracking changes and additions, rearranging keys), but some of them are very error-prone, and require the removal of all tags it creates in the file. Crowdin would be cleaner and easier.

**Comment by pmotschmann** [comment]
Ok I'm looking into it finally.

**Comment by pmotschmann** [comment]
Well it looked interesting, but Crowdin appears to be unsuitable due to a 5000 string limitation on open source projects.
