### ISSUE TITLE
Selenophobia Breakdown

### ISSUE THREAD

**Issue by pmotschmann** [pmotschmann/Evolve#47]
The Arraak race has a trait called Selenophobia which makes their production fluctuate with the moon cycle, this needs to be reflected in the various production breakdowns.

**Comment by CapnCrinklepants** [comment]
I'm going through all the resources because knowledge still seems to not calculate properly, or at least I can't figure out how to calculate it manually so I want to clean up the breakdown stuff there too. I'll add in Selenophobia when I find it affecting something.

**Comment by pmotschmann** [comment]
I'd probably go with "Moon Phase" for Selenophobia. This unfortunately causes another problem because the way I wrote the breakdown system it doesn't allow for a space in the label name or it breaks. It might be easier to just label it as "Moon" for now.

Skittish we can just label as "Thunderstorm" and likewise Nyctophillacs can add a label of "Cloudy", I think those are perfectly clear.

**Comment by pmotschmann** [comment]
Calculating the Knowledge breakdowns, you should just be able to apply the line items from top to bottom in the order they are listed and get a mostly accurate result; it could be off slightly because of rounding errors but this variance should be very minor.

**Comment by pmotschmann** [comment]
Here's an Arraak save file you can use if you are going to debug Selenophobia
[Arraak.txt](https://github.com/pmotschmann/Evolve/files/3158116/Arraak.txt)

**Comment by CapnCrinklepants** [comment]
Thanks! Also here's what I get for knowledge on my debug file. It's a similar large gap on my main game

![image](https://user-images.githubusercontent.com/474882/57388108-67990900-716c-11e9-93d4-305d8ebc2dd4.png)

**Comment by pmotschmann** [comment]
Adjust Professors is a synergy upgrade which makes Scientists stronger depending on how many professors and wardenclyffes you have. The bonus is suppose to be applied to scientists. This upgrade makes scientists strong while keeping professors relevant.

**Comment by CapnCrinklepants** [comment]
Oh I get it. durp
