### ISSUE TITLE
bug: can't queue pillars

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#474]
bug: can't queue pillars, even when I'm only waiting for the scarletite to stack up.

also the tooltip says it's called "Circle of PIllars" whereas the button says "Ancient Pillars".

**Comment by Beorseder** [comment]
It's intended that you can't queue them, and tons of buildings have text at the top of the tooltip different than the building name. EX: Wardenclyffes, Universities, Banks, Rock Quarry, etc. That text at the top of the tooltip is a descriptor, not necessarily just reiterating the name.

**Comment by lxsli** [comment]
OK cool
