### ISSUE TITLE
Memory leaks of version 1.0.13 on FireFox 83.0 / windows / 64bit

### ISSUE THREAD

**Issue by blacklion** [pmotschmann/Evolve#486]
I run 1.0.13 on FireFox 83.0 (latest) under Windows.
After several hours of play I see this:

```
Explicit Allocations

5,930.86 MB (100.0%) -- explicit
├──5,140.83 MB (86.68%) -- window-objects
│  ├──4,736.81 MB (79.87%) -- top(https://pmotschmann.github.io/Evolve/, id=151)
│  │  ├──4,512.79 MB (76.09%) ++ active/window(https://pmotschmann.github.io/Evolve/)
│  │  └────224.02 MB (03.78%) ++ js-zone(0x22739216000)
```

And it grows. Previous browser instance grow to ~10GB in a day.

This were not a problem for previous months, and starts about week ago.

I've seen, that v1.0.11 fixed memory leak, but looks like it is still here.

**Comment by pmotschmann** [comment]
was addressed in f9894a5070ff6638e787eb1cb0153c6b0e7f6aad
