### ISSUE TITLE
ARPA projects on `[Never]` block other completions

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#488]
Sometimes when I have an ARPA project queued that can't ever complete, EG a stock exchange due to missing crafted mats, other buildings in the queue which could complete sit there on `[0s]`. Supplying the mats and letting the project finish fixes it; removing it from the queue also works. I have "build queue order" turned off.

**Comment by mart0258** [comment]
Bug is found at main.js:6761. It checks if there's less than 1 second remaining, but "never" has an extreme negative value that isn't accounted for.
