### ISSUE TITLE
Resonance achievement becomes hard to upgrade

### ISSUE THREAD

**Issue by lxsli** [pmotschmann/Evolve#489]
I've been working on a 4* technophobe run (mmm tasty souls). I figured I may as well upgrade Resonance while I was here. It turns out that it's not possible to do that with my current race, as I've already fused one. What happens when I've done all 43? Will it be impossible to upgrade this achievement?

**Comment by Beorseder** [comment]
When all species are Pillared, then simply researching Scarletite will give you Resonance.
