### ISSUE TITLE
Launch bug on latest version: undefined obj on line Line 374

### ISSUE THREAD

**Issue by skullytheskully** [pmotschmann/Evolve#499]
v(t.version) < 100015 && t.race.cataclysm && (t.settings.showPowerGrid = !0),
    v(t.version) < 100016 && (["l", "a", "e", "h", "m", "mg"].forEach((function(e) {
        t.stats.spire.hasOwnProperty(e) && t.stats.spire[e].hasOwnProperty("lord") && (t.stats.spire[e].dlstr = t.stats.spire[e].lord)
        
        /*this is where the error is being thrown according to my console*/
    }
    )),
    
    
    Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at main.js:1
    at Array.forEach (<anonymous>)
    at main.js:1
    at main.js:1
    
    looks like a simple enough fix but figured it was worth pointing out

**Comment by pmotschmann** [comment]
Fixed in 6162d901eae9088c66b0991110b27ebbfd48e58d
