### ISSUE TITLE
Citadel uses 5MW per Additional Station

### ISSUE THREAD

**Issue by enkido** [pmotschmann/Evolve#511]
Citadel uses 5MW per Additional Station v1.0.24

Active Stations | Total Consumption | Difference
---------------- |---------------- |----------------
0 | 1641 |  --
1 | 1671 | 30
2 |1706 | 35
3 |1746 | 40
4 |1791 | 45
5 |1841 | 50
6 |1896 | 55
7 |1956 | 60

**Comment by Beorseder** [comment]
What you're observing is the intended mechanic, so good. You're framing it in a different way, but it's still the same mechanic of the power cost of Citadel Stations increasing by 2.5MW per active Citadel Station.
![Citadel](https://user-images.githubusercontent.com/45007766/105176217-30a28c80-5ae2-11eb-8f37-4ef34263948e.png)
Going off of your numbers:

Active Stations | Total Consumption | Total Consumption from Citadel Stations | Total Consumption per Citadel Station
-- | -- | -- | --
0 | 1641 | -- | --
1 | 1671 | 1671 - 1641 = 30 | 30 / 1 = 30
2 | 1706 | 1706 - 1641 = 65 | 65 / 2 = 32.5
3 | 1746 | 1746 - 1641 = 105 | 105 / 3 = 35
4 | 1791 | 1791 - 1641 = 150 | 150 / 4 = 37.5
5 | 1841 | 1841 - 1641 = 200 | 200 / 5 = 40
6 | 1896 | 1896 - 1641 = 255 | 255 / 6 = 42.5
7 | 1956 | 1956 - 1641 = 315 | 315 / 7 = 45

**Comment by enkido** [comment]
Ok, i thought the increased power consumption  is only for the additional installation and not retroactive for the others.
