### ISSUE TITLE
Bug: Cancelling an item in the queue will break tooltip timer predictions

### ISSUE THREAD

**Issue by boozledorf** [pmotschmann/Evolve#516]
![image](https://user-images.githubusercontent.com/7085132/105736081-6a203100-5f02-11eb-9cd3-ee578d36bd51.png)

Sometimes I'll click too many times on something and run out of resources for it.  Rather than wait for it to queue, I'll cancel it in the queue.  Unfortunately, this will then completely break the estimated time until I have the resources for any buildings until I reload the page. 

I can't reproduce it on demand, but it happens at least once a day by accident.

**Comment by pmotschmann** [comment]
fixed in 1.1.3
