### ISSUE TITLE
Achievements not updating mastery

### ISSUE THREAD

**Issue by mart0258** [pmotschmann/Evolve#518]
achieve.js, function unlockAchieve

At the bottom, it attempts to update the mastery.  While calc_mastery(true) should do so, that function uses a cached version of the achivement level that hasn't been updated to handle the new achievement (which is recalculated two lines later with drawAchieve). 

Move calc_mastery to the bottom of the three, and it should have the right information to use. 

There's still an easy workaround, refresh the page.

**Comment by pmotschmann** [comment]
was fixed in 1.0.27
