### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Rare-Account** [pmotschmann/Evolve#527]
Will anything happen if I wait it out
![AC83DA59-544B-4EC6-B54D-261E773DF825](https://user-images.githubusercontent.com/73627004/106827147-eb3b9e80-664d-11eb-8b55-136adcbd6bde.jpeg)

**Comment by Rare-Account** [comment]
Oh

**Comment by Rare-Account** [comment]
![Uploading F3CFBB8F-D198-45A2-A500-9443726B1561.jpeg…]()

**Comment by Rare-Account** [comment]
![Uploading 8CDC3AD8-EA57-4817-AC9B-BF97F50E4267.jpeg…]()

**Comment by Rare-Account** [comment]
![3742AC76-1F4C-4FC3-A788-EF4B7A31F253](https://user-images.githubusercontent.com/73627004/106829375-a3b71180-6651-11eb-8b68-2e06d43aa23b.jpeg)

**Comment by Beorseder** [comment]
Your Plasmid bonus will just deteriorate down to 0% for that run if you manage to reach it. It takes at least 2-3 irl months to reach Decay though, so it's not even a concern.
It's better if you use the Discord https://discord.gg/arUeF3rV or the Reddit https://www.reddit.com/r/EvolveIdle/ for questions like this.
