### ISSUE TITLE
Idea: Add a construct and assign button for crates/containers

### ISSUE THREAD

**Issue by Rare-Account** [pmotschmann/Evolve#530]
I have an idea add a construct and assign button for crates/containers whenever you click on the green plus for a material

**Comment by Beorseder** [comment]
![image](https://user-images.githubusercontent.com/45007766/107338986-64395c80-6a79-11eb-8b89-103e7f48d423.png)
The game already does that?

**Comment by pmotschmann** [comment]
This already exists, unless I'm misunderstanding something here.

**Comment by Rare-Account** [comment]
Yes you are

**Comment by Rare-Account** [comment]
I mean add a button to do it at the same time
