### ISSUE TITLE
Can only buy one transfer station 

### ISSUE THREAD

**Issue by Rare-Account** [pmotschmann/Evolve#532]
After I’ve bought one transfer station I cant buy anymore 
Save: https://github.com/Rare-Account/text/blob/main/E

**Comment by Beorseder** [comment]
![image](https://user-images.githubusercontent.com/45007766/107736772-15313880-6cc0-11eb-876c-3e903b6c75b2.png)
Just bought one

**Comment by Rare-Account** [comment]
Hmmmm
