### ISSUE TITLE
A.R.P.A - Projects

### ISSUE THREAD

**Issue by Jumes-1** [pmotschmann/Evolve#55]
When buying a percent of any of the projects, the hint doesn't show the resources as red if you don't have enough, as you can see below I don't have enough steel to get the next percent.

![Screenshot_1](https://user-images.githubusercontent.com/15107219/57568803-1b57fe00-73e4-11e9-84b7-80735955127a.png)

**Comment by CapnCrinklepants** [comment]
I believe it does show the resources in red at first, but it doesn't update the popup after clicking the button.
