### ISSUE TITLE
Combat/Wounded bug introduced in 1.0.35

### ISSUE THREAD

**Issue by Tro2y** [pmotschmann/Evolve#565]
Soldiers arrive Wounded.

Rather than Wounded count lowering over time, it raises until all soldiers are wounded.

Combat results in the wounded count lowering (rather than raising).

I thought this was just a display thing, but a little testing suggests this is actually affecting the data and combat outcomes are affected. 

save file attached in case needed.

[evolve-2021-4-1.txt](https://github.com/pmotschmann/Evolve/files/6239480/evolve-2021-4-1.txt)

**Comment by Tro2y** [comment]
Appears to be a display bug (only), not functionally affecting combat. Fresh game file just having unlocked barracks attached.
[evolve-2021-4-1 (1).txt](https://github.com/pmotschmann/Evolve/files/6239629/evolve-2021-4-1.1.txt)

**Comment by pmotschmann** [comment]
sounds like the kind of thing that will go away on it's own in ~24 hours.
