### ISSUE TITLE
#egg13 not aquirable.

### ISSUE THREAD

**Issue by TTSKarlsson** [pmotschmann/Evolve#571]
This egg is not clickable, and therefore not acquirable. ( #egg13 )

![image](https://user-images.githubusercontent.com/9962943/113514958-d60dbe00-9571-11eb-8631-0be751e65fca.png)

Environment: Latest Firefox Stable on Windows 10

**Comment by TTSKarlsson** [comment]
Fixed it by changing line 4956 in main.js to ```for (i=1; i<14; i++){``` , but the problem only exists if you compile this yourself which means the fix is there just not committed to this repo yet.

**Comment by pmotschmann** [comment]
there is no bug with egg 13, this change breaks eggs 14 and 15
