### ISSUE TITLE
allow separate choice for queue order on research vs building queue

### ISSUE THREAD

**Issue by jacob-keller** [pmotschmann/Evolve#578]
There is an option "No queue order" which allows you to queue a bunch of buildings and have them built without regard to order. This is a useful option so that you can queue multiple buildings that each use unrelated resources and allow them to finish without being stuck just because one building needs a slow resource that is going to take forever.

However, this option is potentially less desirable for research. It would be convenient if I could enforce queue order for the research queue without enforcing it for the building queue, however this is currently not possible.

**Comment by pmotschmann** [comment]
was added recently
