### ISSUE TITLE
Tooltip for infernite

### ISSUE THREAD

**Issue by hyprtrail** [pmotschmann/Evolve#581]
![image](https://user-images.githubusercontent.com/16047105/116531943-fcf4b100-a8df-11eb-8ab5-2558ff054e8e.png)

Tooltip specifys garage, fortress, and alpha centauri (where it should say warehouse?)

**Comment by pmotschmann** [comment]
Say alpha centarui to distinguish between terrestrial warehouse and interstellar warehouse
