### ISSUE TITLE
Add rocket icon from Launch Day feat to prestige icon menu in settings

### ISSUE THREAD

**Issue by networkinterfacecontroller** [pmotschmann/Evolve#583]
title - there's a new feat called Launch Day and it has a rocket icon. Can this be added to the prestige icons (to swap out for the star)?

**Comment by pmotschmann** [comment]
it's already an icon you can use

**Comment by networkinterfacecontroller** [comment]
oh, oops! guess I needed to reload after getting the achievement :) thanks!

**Comment by networkinterfacecontroller** [comment]
nice cat btw
