### ISSUE TITLE
Timer untill storage is full.

### ISSUE THREAD

**Issue by Julepalme** [pmotschmann/Evolve#59]
Would it be possible to add an option to have timers next to storage/gains to show how many hours/minutes/seconds till storage is full, or empty (perhaps color code for increasing or decreasing materials)

**Comment by Julepalme** [comment]
Perhaps having the information in the storage breakdown mouseover would be plenty, to avoid cluttering the interface too much.

**Comment by pmotschmann** [comment]
That's where I plan to put it, hoping to get it done this weekend.
