### ISSUE TITLE
Please, add some accessible feature for this game

### ISSUE THREAD

**Issue by Giovani93** [pmotschmann/Evolve#63]
Hello.
I am blind player of game Evolve. I have found Your game at:
https://forum.audiogames.net/topic/28828/evolve-a-new-incremental-game/
There are some issues for blind users of this game.
First of all, those clickable items are mostly links. It is very good, but We can use with those links keys for multiplifications, such as ctrl, shift, or alt, because We use keyboard and screen reader, no mouse.
Nextly, reset button is sometimes shown in settings menu. Maybe, It is also for mouse. So, after pressing enable reset button sometimes We must type It many times to show It.
Please, could You look on those issues?
Thank You.
Marco
P.S: People in this forum will be very glad, if You'll consult those problems with You, dear developers and We love Your game.

**Comment by pmotschmann** [comment]
Are most of your issues related to keyboard navigability?

I have the reset buttons hidden behind a switch because I don't wan't people to accidentally press them. This might be causing you problems in locating it.

What screen readers are popular? I know there are free options like VoiceOver and ChromeVox but I don't know if many people actually use these.

**Comment by Giovani93** [comment]
Ofcourse, because blind people use mostly keyboard. Ofcourse, I can use also touchpad, or mouse with those multiplification keys. For blind people It is sometimes strange.
And also, with this hidden switch, It can be also tricky. I am maybe one person, who posted those things here, but maybe I won't be only yourself. I have sent a link to this forum to look on this forum. Also, blind, or noblind, people without any differences can have also great idea.
I use NVDA. This screen reader is free, opensource and is for Windows.

**Comment by Ettanin1987** [comment]
Suggestion regarding hiding the reset buttons: Make them visible in any case, but disable them unless the specific checkbox is checked.

**Comment by pmotschmann** [comment]
Ongoing effort but this doesn't need a general ticket open for it anymore.
