### ISSUE TITLE
saving game

### ISSUE THREAD

**Issue by Harry226** [pmotschmann/Evolve#631]
[evolve-2021-9-22.txt](https://github.com/pmotschmann/Evolve/files/7232216/evolve-2021-9-22.txt)
Earlier today I cleared my browser and cache history, which removed my game progress. I have the game saved but how do I convert the txt file to a JSON file?

**Comment by Beorseder** [comment]
Well you don't need to make it into a JSON file. Just copy the string, paste it into the save string box, and press Import Game.
![image](https://user-images.githubusercontent.com/45007766/134835332-0478fd95-5a45-4350-82b9-5edec8f7ac99.png)

If you read the tooltip for the Load String Pack button and thought that had anything to do with your save it's something completely different.
https://pmotschmann.github.io/Evolve/wiki.html#mechanics-gameplay-spack

**Comment by Harry226** [comment]
ohh ok thanks that helped!
