### ISSUE TITLE
Craftsmen Locked After Fanaticism

### ISSUE THREAD

**Issue by Aurah** [pmotschmann/Evolve#64]
When taking the Fanaticism tree, with your previous species being a woodless one, if you have any workers in Plywood manufacture, they will be inaccessible.
![image](https://user-images.githubusercontent.com/16437137/57616402-e380c000-7575-11e9-8ee8-e179f0668655.png)

**Comment by pmotschmann** [comment]
Fixed by 733ce061aae32ebd94ab2c3e5a35aeca6768b99b
