### ISSUE TITLE
Bug: Space Stations after 1 do not increase max Miners

### ISSUE THREAD

**Issue by CleanCutBloons** [pmotschmann/Evolve#652]
Powering on one Space Station gives me three Space Miner slots, but powering more does not increase it.
Version 1.1.17

![Screenshot 2021-11-30 132256](https://user-images.githubusercontent.com/61286931/144105559-60717884-763f-46b2-92f0-fb1fdfa31ec5.png)

**Comment by Beorseder** [comment]
Each powered Space Station lets you assign 3 more citizens to the Space Miner job. For each person in that job, your Asteroid Belt support increases by 1. Are you sure you haven't just not assigned more people to the job role? If so, paste save.

**Comment by pmotschmann** [comment]
You have to assign space miners

**Comment by CleanCutBloons** [comment]
Ok, got it. I thought Space Miners was like other space support, like
Pincer Support.
