### ISSUE TITLE
Bug: junk gene

### ISSUE THREAD

**Issue by DSLM** [pmotschmann/Evolve#662]
Would we still get trait which isn't gained? It looks like junk gene will make it strong.
https://github.com/pmotschmann/Evolve/blob/master/src/actions.js#L7055-L7086

**Comment by pmotschmann** [comment]
works as intended.

**Comment by DSLM** [comment]
> works as intended.

  "wiki_challenges_genes_crispr_para2": "With this challenge active, you will also randomly gain a negative trait that your species does not already have.",

However it wouldn't reroll. Maybe wiki description is wrong?
https://github.com/pmotschmann/Evolve/blob/master/src/actions.js#L7064
