### ISSUE TITLE
Intergalatic tech tab doesn't load

### ISSUE THREAD

**Issue by nystik** [pmotschmann/Evolve#664]
https://pmotschmann.github.io/Evolve/wiki.html#intergalatic-tech doesn't have any content

This also manifests differently when clicking through the UI -> when clicking the text, it doesn't change the URL to the anchor. It seemingly doesn't have any content (though from what I can tell it's all still there), and therefore doesn't finalize all the auto-generation of the anchor/mainContent/etc

I tried to poke around and see if there was a quick oversight that I could contribute a fix (👍 game and wanted to help ), but alas, I failed.

**Comment by Beorseder** [comment]
Well you spelled "intergalactic" wrong in the url.
Correct Link:
https://pmotschmann.github.io/Evolve/wiki.html#intergalactic-tech

Works for me. If that link doesn't work for you, then paste save.

**Comment by nystik** [comment]
Doh!
Tried the link (and wiki) from both latest firefox/chrome, and still not loading. The UI not changing the URL is still a thing as well (both browsers).

**Comment by nystik** [comment]
I just checked and it's working now. Don't know what changed, but it looks as though things are all set :)
