### ISSUE TITLE
Bug: Smoldering races still don't loot Chrysotile

### ISSUE THREAD

**Issue by yunenliu** [pmotschmann/Evolve#691]
I saw you fixed the first bug around Chrysotile looting, but Chrysotile still isn't being looted. It looks like there's no case for Chrysotile when choosing gains in the case statement below. Also more generally, if I am reading the code in civics.js correctly, even if this is fixed smoldering races can attempt to loot lumber, which will sometimes lead to no loot. Perhaps lumber gains should be replaced by Chrysotile after loot amounts are established?

**Comment by pmotschmann** [comment]
fixed in 1.2.8
