### ISSUE TITLE
BUG:korean strings pack is not working

### ISSUE THREAD

**Issue by sirspect** [pmotschmann/Evolve#731]
![asdf](https://user-images.githubusercontent.com/97418702/157133677-9daf670a-f36f-4b80-913d-95b720458c5a.png)

korean strings pack is not working. plz fix this bug.

**Comment by Beorseder** [comment]
You caused this bug by introducing several json formatting errors during translations you did. Mainly either omitting a comma or a quotation mark at the end of some lines.
