### ISSUE TITLE
Bug: ARPA Railway and Supercollider switched

### ISSUE THREAD

**Issue by aivct** [pmotschmann/Evolve#745]
**Unexpected Behaviour:**
![bug_a](https://user-images.githubusercontent.com/79041835/161233981-f350b9bf-d9d8-44cc-af52-26caea028d42.PNG)
Not only are they in the wrong positions, but they use the wrong resources to upgrade (the tooltips are correct in that it uses titanium to upgrade a railroad, that is titanium is consumed when upgrading).

**Steps to reproduce:**
Use attached save file on v.1.2.13, go to ARPA tab, and click on any of those two buttons.
[evolve-2022-4-1.txt](https://github.com/pmotschmann/Evolve/files/8396390/evolve-2022-4-1.txt)

**Comment by Saucistophe** [comment]
...And genes and soul gems, and coal and oil...
April's fool?

This takes a bit of time to get used to, and cost me a few dumb moves on my current BH run, but it was funny. A bit.

**Comment by Saucistophe** [comment]
Yeah, yesterday's commit that bumped to 1.2.13 is here:
https://github.com/pmotschmann/Evolve/commit/4bf0ee53d6c540bb0ed26681bca27d655bbcd7e9
...And it uncomments a bunch of lines tagged as AFP (April Fool Pschomething?)

**Comment by aivct** [comment]
Whoops, I was playing at midnight and forgot about the date. I see, it's just the names are switched, nevermind.
