### ISSUE TITLE
Bug: Truepath Habitats still bug out with 8 of them becoming unusable

### ISSUE THREAD

**Issue by braindoper** [pmotschmann/Evolve#757]
This bug has been around since Truepath got introduced. I don't know what exactly triggers it, but it might have to do something to do with building habitats without enough support. Precisely eight of the habitats become and permanently stay unusable, even if enough support is available and even when the save file is exported, once a certain number of habitats is turned on.

I attached a save file where the bug can be observed. Currently 8 habitats are turned on, and there are 8 colonists available, with plenty of support to spare. Once the next habitat is turned on, only habitat will remain active (as in consuming support and colonist spots), while eight of them become unusable.

[evolve-2022-5-4-17-50 truepath habitat bug.txt](https://github.com/pmotschmann/Evolve/files/8622017/evolve-2022-5-4-17-50.truepath.habitat.bug.txt)

**Comment by Vollch** [comment]
Habitat consumes 500 food/s. Game ticks 4 times per second, that's 500/4=125 food per tick. 8*125=1000. 
And that's exactly your food storage cap. That's where all that happens:
https://github.com/pmotschmann/Evolve/blob/498b8864869afb935432f040abe0368861de6198/src/main.js#L1820
Get a silo, and you will be able to run all your habitats.

Hard to say really, whether it's bug or not. There's a lot of of inconsistency how different things consume resources.
(Tho, i don't really like how support check first loops over fuels, and then over buildings. Looks like it can burn extra fuel when first resource is enough for e.g. 10 buildings, and second fuel type just for one, it this case 9 packages of first fuel will be wasted for nothing.)

**Comment by universeexplor** [comment]
So,I have a question……I am a rookie,what is truepath?And where will it unlocked?
