### ISSUE TITLE
Trade when full bank/resources + possible feature

### ISSUE THREAD

**Issue by petakii** [pmotschmann/Evolve#79]
If you sell a resource, but your bank is full, the resource is taken away, but your money won't increase. The same happens when you buy something with full storage, you lose the money, but get no resource. Trade routes do the same, they buy/sell when they shouldn't.  It would be nice if an error popped up saying "Your storage is full! / Your vault is full!", or something similar.

A possible feature related to this would be autotrading the excess resources from battles, when storage is full. (Until your bank is full) Better than wasting it.

**Comment by blindley** [comment]
I like the first suggestion. The second takes away your responsibility in properly managing your storage space, which I feel is an important aspect of this game.
