### ISSUE TITLE
Governor Crate/Container Management Inconsistent When Using Advanced Setting

### ISSUE THREAD

**Issue by MrFluffums** [pmotschmann/Evolve#792]
When using the "Advanced" tickbox under the Governor's task "Crate/Container Management" some materials will be left with unusually low Crate/Container assigments. I've been spamming MAD runs and noticed this has happened with several races.

Currently, settings and results are as follows:

![image](https://user-images.githubusercontent.com/39612534/185413521-0370edb6-bba9-44a5-9182-7c69b24f0d43.png)
![image](https://user-images.githubusercontent.com/39612534/185413591-1bab5c70-301b-42b0-be5d-742cdb97a3b9.png)

I frequently have Furs and Coal set to 1/2x or 1x, and I notice these two resources in particular often have fewer total crates assigned between them than would be expected. The issue is most egregious when they are set to 1/2x. In this case, both Coal and Furs are set to 1x, so one would expect that the number of crates assigned would be somewhat similar, but the amount of crates assigned to Furs is 11, while the number assigned to Coal is 1, with an expected number for both of 6.

It seems there's some resource order/priority system that determines which resource receives crates first if there is an overflow, and/or it seems like resources set to lower numerical denominations (1/2x, 1x) are deprioritized in favor of the higher denominations (4x, 3x.)

This can be modified to produce further baffling results:

![image](https://user-images.githubusercontent.com/39612534/185415137-d73fecda-309f-4f25-9e7b-9ea883be4711.png)
![image](https://user-images.githubusercontent.com/39612534/185415165-1e47f94d-0a2b-4771-b304-4989014910e5.png)

Here, Furs are set to 1/2x while Coal is set to 1x, yet the Crate assignment to Coal is 1/4th the amount set to Furs, when the expected behavior in the worst case would be the reverse.

Save File attached, but this is not tough to replicate in my experience, as almost any configuration that includes settings for all 6 priority denominations results in this behavior.
[evolve-2022-8-18-8-59.txt](https://github.com/pmotschmann/Evolve/files/9374464/evolve-2022-8-18-8-59.txt)

**Comment by pmotschmann** [comment]
It works the way it's intended, the game is doing you a favor by not assigning large amounts of crates to coal, food, and fur.
