### ISSUE TITLE
Translation issues for Chinese

### ISSUE THREAD

**Issue by LoveBodhi** [pmotschmann/Evolve#801]
- [ ] city_basic_housing_desc_plural - "%0位市民的基本住房"
- [ ] city_forge - "锻造%0",
- [ ] city_forge_desc - "锻造%0",

Currently is empty, so it displays English.

**Comment by NeutronCollider** [comment]
大佬，请问翻译组是解散了还是发生了什么，我有一些关于新游戏模式翻译的建议

**Comment by NeutronCollider** [comment]
本来编辑了一版翻译想发出来，结果因为网络波动功亏一篑了

**Comment by LoveBodhi** [comment]
不过，可以 Fork 的……

**Comment by NeutronCollider** [comment]
非常抱歉，因为没有接触过代码，gh也是昨天才注册的，我提供翻译文本可以吗？
