### ISSUE TITLE
CN translation of Orbital Decay

### ISSUE THREAD

**Issue by NeutronCollider** [pmotschmann/Evolve#809]
"wiki_challenges_modes_orbitdecay": "轨道衰变",
  "wiki_challenges_modes_orbitdecay_para1": "%0 是一个月球位于衰变轨道的挑战（这个挑战中，月球将在一定天数后撞击地球）,",
  "wiki_challenges_modes_orbitdecay_para2": "你的本周目游戏起始于世界末日的 %0 天之前。",
  "wiki_challenges_modes_orbitdecay_para3": "你的游戏目标并非躲避这场地月撞击，而是要让文明能够进入太空从而在撞击后幸存下来。",
  "wiki_challenges_modes_orbitdecay_para4": "撞击发生时你将同时失去你的母星和月球在太空中的位置。",
  "wiki_challenges_modes_orbitdecay_para5": "%0 挑战模式完成的条件为进行地球化重置。",
  "wiki_challenges_modes_orbitdecay_para6": "这个重置要求游戏进入最后的 %0 阶段",
  "wiki_challenges_modes_orbitdecay_para7": "如果您使用了其他重置方式结束本周目游戏，将不会获得任何有关该挑战的挑战成就等级。",
  "wiki_challenges_modes_orbitdecay_para8": "地月撞击发生时，您有可能以完全失败的结局结束本周目游戏。",
  "wiki_challenges_modes_orbitdecay_para9": "飞升重置在本挑战中不可用，它被替换为地球化重置",
  "wiki_challenges_modes_orbitdecay_para10": "游戏达到以下的关键点时，轨道衰变的速度将会增加。",
  "wiki_challenges_modes_orbitdecay_para11": "建造 %0 将会把剩余天数降低至 %1 （前提是剩余天数大于 %1 天）",
  "wiki_challenges_modes_orbitdecay_para12": "建造 %0 或 %1 将会把剩余天数降低至 %2 （前提是剩余天数大于 %2 天）",
  "wiki_challenges_modes_orbitdecay_para13": "建造 %0 将会把剩余天数降低至 %1 前提是剩余天数大于 %1 天）",
  "wiki_challenges_modes_orbitdecay_para14": "不可以和 %0 剧情模式一起进行。"

**Comment by LoveBodhi** [comment]
"wiki_challenges_modes_orbitdecay_para14" 应该是“无法与%0剧情模式同时激活。”

**Comment by NeutronCollider** [comment]
已上传pull request（虽然操作可能有问题，不知道怎么上传json）

**Comment by LoveBodhi** [comment]
> 已上传pull request（虽然操作可能有问题，不知道怎么上传json）

需要先 Fork，再上传文件，之后发起 Pull Request。
