### ISSUE TITLE
Cacti deifing BUG

### ISSUE THREAD

**Issue by LoveBodhi** [pmotschmann/Evolve#810]
When I research `Deify Ancients` (神化先祖) by getting `Cacti` (仙人掌) 's main trait (After next 2 runs), it re-appears in the "research" tab instead of vanish after auto refresh.

That means two different trees can be researched together after 2 runs of cactus, which breaks the game rule. This is not a thing should be expected!

**Comment by pmotschmann** [comment]
This should be fixed as of 1.3.7
