### ISSUE TITLE
The PT-BR translation needs to be updated

### ISSUE THREAD

**Issue by villanovasoft** [pmotschmann/Evolve#832]
Hello community!
I would like your authorization to update the file "Evolve/strings/strings.pt-BR.json", regarding the translation in Brazilian Portuguese. I compared it with the "Evolve/strings/strings.json" file and some strings are missing in the "../strings.pt-BR.json" file, which causes untranslated terms.
Can you authorize me to make a pull request for the next version?
I am waiting for an answer.

**Comment by pmotschmann** [comment]
The translations are all community submitted, you are certainly welcome to submit an update to Portuguese language file. This hasn't been updated in quite some time as the person who used to do them hasn't been around for a while.
