### ISSUE TITLE
Filling Tauceti (天仓五) and other new strings for ZH-CN Translation

### ISSUE THREAD

**Issue by LoveBodhi** [pmotschmann/Evolve#836]
It's a part of Truepath (智械黎明).

**Comment by LoveBodhi** [comment]
Also welcome @NeutronCollider 's help.

**Comment by LoveBodhi** [comment]
We don't gonna use g8hh's unofficial translation, we should translate them by ourself.

**Comment by universeexplor** [comment]
I think "套娃计算机"is too ugly,how about"递归迭代计算阵列？"

**Comment by LoveBodhi** [comment]
`递归迭代计算机`就可以……

**Comment by universeexplor** [comment]
空间跳跃门可以改为远距传输器，也算致敬《海伯利安》了

**Comment by LoveBodhi** [comment]
> 空间跳跃门可以改为远距传输器，也算致敬《海伯利安》了

我这里叫“跃迁之门”。

**Comment by LoveBodhi** [comment]
G8HH 部分翻译还存在一些问题（例如语法错误、机器翻译等）……

**Comment by LoveBodhi** [comment]
Distribute Low Power 是“分配低电量建筑”，可惜没有对应的字符串……

**Comment by LoveBodhi** [comment]
`辛迪加`和`外域船坞`是智械黎明的，这两段到时候再翻译吧……

**Comment by universeexplor** [comment]
u1s1，真希望能出个关于流浪地球的剧情模式

**Comment by LoveBodhi** [comment]
不知道 challenge 是什么新的挑战模式……

**Comment by LoveBodhi** [comment]
将来的新挑战是因宇宙而异的……

**Comment by LoveBodhi** [comment]
更新一处就得汉化一处……

**Comment by LoveBodhi** [comment]
没有 G8HH 的参考，难免会有语法错误，或者语句不通顺的问题……

**Comment by LoveBodhi** [comment]
原来我只是不认同 G8HH 的版本，因此改为：如果对汉化有什么问题可以来找我。
From now: Feel free to feedback to me for ZH-CN Translation now. No more G8HH objection.

**Comment by LoveBodhi** [comment]
[有关修格斯的介绍](https://baike.baidu.com/item/%E4%BF%AE%E6%A0%BC%E6%96%AF/8544337?fr=aladdin)

**Comment by LoveBodhi** [comment]
这个 Eldritch 种群的生物需要查找有关克苏鲁的资料才行。

**Comment by LoveBodhi** [comment]
我得先重修语文，然后再来进行一次全面汉化……（这次以 strings.json 为基础）

**Comment by LoveBodhi** [comment]
奴仆的介绍好难汉化呀……

**Comment by LoveBodhi** [comment]
Corsair 是海盗船的意思，不过还是叫`掠夺者`较为贴切。

**Comment by LoveBodhi** [comment]
I'll close this issue once the PR got merged.

**Comment by LoveBodhi** [comment]
Move to #915
