### ISSUE TITLE
[BUG?] 1.3.2a, Soul Gem drop rate

### ISSUE THREAD

**Issue by Kaguya4649** [pmotschmann/Evolve#843]
To respectful dev,

Several players found that the drop rate of soul gem has been dramatically decreased to about only 1/10 compared to the previous version. And when we checked the source code, we found a condition which is:

 let final_chance = gem_chance -killed +40;
if (final_chance < 75) {final_chance = 75;}

Does it mean that the drop rate cannot exceed 1/75? Because the enemy killed will be as large as around 100 even 200 every patrol.

However, the maximum drop rate was 20% at the previous version, as long as you had enough Attractor Beacon. So maybe there is a bug, please check.

**Comment by LoveBodhi** [comment]
If this is a BUG, I must do Blackhole Reset.
