### ISSUE TITLE
Bleed CRISPR Upgrades disappeared

### ISSUE THREAD

**Issue by DrLucky007** [pmotschmann/Evolve#845]
Hi there,

I recently noticed that several of my CRISPR upgrades went missing:

Bleeding Effect (Bleed 1)
Synchronicity (Bleed 2)
Astral Awareness (Bleed 3)

I noticed this when I went to CRISPR and had the option to purchase Bleed 1 again.

I recently upgraded to 1.3, though I'm not sure exactly when. I also recently BHed back into antimatter from a brief stay in Micro.

I have relatively frequent saves, so I can provide a pair of saves before (with the upgrades) and after (without).  Those saves occurred on March 2, 2023 about 10 hours apart.

I don't play with any tools / cheats / whatever.

I'm not sure if anything else went away.

**Comment by pmotschmann** [comment]
There was roughly a 6 minute period where the game was bugged and would remove those upgrades on March 2nd. If you were unlucky enough to load the game during that window then they got deleted. It is not an issue you have to worry about occurring again. Sorry you were affected by this but there is no way for me to detect games that got hit by the bug. You can however use a save editor to add them back in.

**Comment by DrLucky007** [comment]
Ha, just lucky I guess!   Not a big deal if it's fixed.  Thanks for the quick response!
