### ISSUE TITLE
An error occurred when setting the language to Korean

### ISSUE THREAD

**Issue by dadofss** [pmotschmann/Evolve#864]
When I set the language to Korean in the settings, the strings are displayed in English. Until yesterday, the Korean setting was working properly, but today this issue occurred.

**Comment by dadofss** [comment]
In the updated file strings.ko-KR.json (#859), there is no comma at the end of line 4980. After extracting the code as a TXT document and modifying it accordingly, the string pack loads correctly.

**Comment by pmotschmann** [comment]
fixed

**Comment by dadofss** [comment]
Thanks
