### ISSUE TITLE
Bunk beds getting reset after a successful siege?

### ISSUE THREAD

**Issue by ThePiachu** [pmotschmann/Evolve#872]
I'm playing some moldlings. I recently got Bunk Beds which spiked my garrison to 57, which I used to Siege another nation and won. A bunch of my soldiers died in the process, and when they regenerated my soldier cap was down to 37:

![image](https://user-images.githubusercontent.com/964559/230483006-77a0cfda-517e-4652-9042-588ed325d7ad.png)

Now sure what exactly caused it, but I'm guessing some of this might be related?

Here is my save:

[Moldlings.txt](https://github.com/pmotschmann/Evolve/files/11174113/Moldlings.txt)

**Comment by pmotschmann** [comment]
Occupying a city by sieging costs 20 soldiers.
https://pmotschmann.github.io/Evolve/wiki.html#mechanics-gameplay-occupying
