### ISSUE TITLE
[bug] Bilateral Symmetry DNA bonus is not applied

### ISSUE THREAD

**Issue by ambre-m** [pmotschmann/Evolve#895]
I'm playing 1.3.6 and during evolution, the "Increases DNA generation from nucleus" effect of "Bilateral Symmetry" is not applied.

I suspect that "Poikilohydric" and "Spores" could be affected too.

**Comment by ambre-m** [comment]
here is a save with the problem:


N4IgzgphAmIFwHYAsBGAbAGhAdwIYCdIZ4BWAZgE4yAOLfCMAewFd8BjCeUAJQDkBBLiAB2uALac4IPoKzQAlmAAOAG1wBPeABd8zCFnEthW+CgoAGLGNwAPUxbnyAZk/hpzAOiSYQ0CCq1ceEsQfFwtSRQsNjCIsGDoxmNceWEIQmCAXywAEQEhUQl4EDzZX0VVDW1dfRBDZmNTFGoPFAQ0NCQEChILJHMEK1t7EIUXUzQPNAAmOX9AhNDwyOjYhkW2JMDU9Pi4c2yQAFkkiE04UELJEAASEEdlNXOnXBVIAzEjE32huzgUcyAxzjH6+eZBUFrUxYMCBNgAa1wACMVJIXm9ajFlnsQptkjsMvtDkp8IwtIxKmAxAVxNcAAqk8mU6kPSrPV7vOqfBrfELWP6jZyuUF+AIQkJQ0Gw3AI5Go+DozlYuIbLYpNKEg5YADKagAbpJLrTirrcAb7uVHlU4IravVGqD+YsxsLRuDFpKQtLZSi0RzMWscYl8RqcYcjrhRDSilII1HWU8Ff6Pl9Fk6RULne7IctoSAAOYQYSLQvCAD6sClcMRvqTGNW2NVId2WSwAGlhIxsKjoIXo9cO12e32E9bbSmeWnhv8geUQW6xR7c/8YdW5X76yBletQXjtqHWyAAFpF/vFE/CAAEdK76QtCit7M39t5v2dmZF2Yly69a9rNuTLdAybfcWyJLAAGFgIuERjSkKDc1HJ9ORfKcBWBV05kXHMIkWb0a3lADN23IMtzVAkw0g8iDxgq5igg6i7yQusUO5B0+WnQV5ywhYcMkX8ZQIjclWg3FGM1Q4ADFGEYSsjRjEBpNk+8KkTIjOT1V49FICd2LfOBphILjMLBbDv1wldwD/QidD0BsVV3cTSJ0XA/EPAAZZgxCRO9aLgkBPO8pjLTZFjak0lRtLgEhdNfEB02mWcXSzMy6GXKIrME9dqjsoDG0c5tNSwFy3PAkAIIAC3wdQmC0eRCPk65Kuq2r6s4Zj1PCrTJBirlU0dadEuMlLePMlZMp9GyansncxMK5ywlKrUQG1ck0jPKRVtOFTHzCrAIqi3rUIGv4howkbxTSiyMvw7K4FsgN8rm0CipAEr+MOKCasCFQNvKlqfp20LOv27q3FitD4DOucTNFUarvG27/wembSL3dUwJCd7D0k1g9ka4pcYyDrxxAA7JFoPrJxO0wko/Bd4aWa7Vyy5Hpryhznox17sbKhilCUXyCfgilBfwIG1NJ8moaOti4vTAFhs/VKmcR6zJBRjnZuDF6Ftcj6sAASVJYs/IU42kglsdAOluB+ghmmZyVhnLtVvMkam3KSJA7m9aWw5+EisRUnkLy/sDryQ7DkmbbB6KQmOji/iM87lcZyUbvVnLHs5nXfcWXnlogiAJAdYXypLosTBjzdbZQWX+qT2nnZ412M5ZyaNfZ72Ct1gvFoN8rGFeP6GJHmuNLjxKHab+PU5dpdmYmoTs9Rn2KP7/XDwAeXqv7d9+ieusiyQEAb6nZ5b0z0/SjuV5BrW0aczf/awABVMJhFD6kzeuD/I2/lbZCx9DopypnpeK04ATz1bovNWrNCKkx7lzDeoJC6HFWlAX6v8TQRH8EAvaZM46KxnvpMByU05t1vsvO6mtkF51QVjAeh4AAq8hAhfzDjgqQbCOGAKPqDE+pgwGJzIVfOGVCl4ey7l7USDCaJMK3mVQOKhGDnHLiotRBCH62zICIuWkM54wwunA92Wd7rdzkWReaL9B43hUOoCQ4tuEgHsY44KD5gZSynvoxuYiYHX0kfAzuq9H7rwUcVZhZVjbyAUFw8uMS4kshCpLWOQi7bT3AfLTiASJGmMstI0J9DrF9zQVE5aAAJfw38yxkD+lUlQ38AC0dSBFEPSTMBOBjHbiK/AjMxCDhI521iU/OZSlHLQAOrLGceXaZERxZtNtrMLJhjekq3bjQ/8SCrHo0YYcHIEBmALMAS4w5xz0j8JSdbWuccehdL8ZA9CxjKH5MzoMwhxS9kKMOLwI5OgkinPLn845JsrmeNSbc9J9dZyiKee+bigS3l3zujsp68jMYB2gOISMdULIaOxdYYw7D2rXOAYIqK0xDIPIvvpdZN8pHmLobs5+0ThBOHSF/fFsFzbss5SS7R3j0nTDPjSiB6Z6VBIGSEh+XzWXLQAKKonwECnl1wlWXOjmSwhyzARiuyX8DKFCF58WlffNFudRn7KwLwSMjAywsOYD5P6trOyXkdc6pZcdRWkPhRmRFeTTUFPMRakZ3zMVYAAOJhCUBVIsho1XFGjbgWN8bBVpKimQPVvqJW5L6W7YNHyLGyPRVan5OoOFppcatSMaavXpLIO4fVay80bOoYU4twyn42LKgAIUYKo/MnCf7l37YO4d6aoVRQsLC7pl9W0MuCffZlpbw0SSwAANXYfQVR6jE1SC3TofwWj61RQBNDOFuaXkmrGma2hljV3ysONvFVbAKqvDYPE/dIAX3yDfR+rVEKbmT3SRQGdzaekLqlYWmVK7LVrsoiAN+nYkT7lVXRKQyHGCofVOC1SwG7RzrpVB5FWzEGATlT25aEYTkcj+jRy5dG2mXpyde2BQb3kytDd20plTGCEAYBVRgCaMMgAqfxyAYAhOkqA+S9pUUIOzyaSs417Hb1ViLdx8JEaQCuoFS4vTuFT38Rzax1TSKOMou2RRllVHDiRvjfjb9Dm0jxGM4sFjfxlMkaDQJLjNnH12Z1CwFQZYHMju/dqELl5wuTpAwp0zXmVP0zU/0jT/niK2d44cOkDjsAyTkt+3L6h8vKWY0Rv1TSjUpYs+pvz5qAvwafVgXtr74R/Va3+9r5XHnpiqz5urVnyOZcC9lrAkzSTMHzBVLQZYLamzmZN6bWhLzzbi4R3r05+tsdq2l+rqLGthuaytONEBZtHDOyPatp2VsXcBj12llXqsBvzZ6IbQy169zGdR9QWgqp7xcUcX7/3D7aofp5+A23zOBsG2Rj7YSvvWpAPwdIjBCzYI0aj9H63EuQ+e7DV7P53ufKy9935drsAQDNCJ/yrrbzU5x6sx2UOasw728T2VpOkfajYAQVEeKacKR53zs7AqHviq2/jkxvmOdacR+WkAABFZguL0P+WV6rwD+G5MQ7gCzl7baLL7esyNprQWh74F0EoWbsWXEMUt8wa3l4ovMBUDFkujPbaKf0t5nbbOC3G+GyJUbZOqJ+D+OXBi4fPdx295V5LBvF14RDYdnjofyryFTbM79CrhAxHUNbmAl4cjhCCO50EuvJWkY7XLlBCvDmfC/mwMsCqwCQDz4L64DfAVsEvK39vHAY/pLj31hPBPDcmbhyTkP+zDgQD1AO458hLYwWgFGSyEhvKfwTZsamSBDj8fzLWlQqInO74dNQQ4whmBsFRMwM//USBz+YIiaqZI/1lg4CfoQ5/vjTEOMHOSG+kkNACqhCKAL/qYIcE4KkFdtQMtBEG+kIH9hAAOmjucBlAAI56BnpYDz6MA6QgD4FlgALWDYIZTEGpCQBsDkixJ5jEHWBiBkF7AUEL5lgQD5j5hSb+DkF4FsG4DYHhB/r0FsEcoYF8H2pgCRiVisH2pxrhAiH2pKADoEBQHRDsJ7q86ojCDYrZ7YrnAhDqBU7OIhCU7hBxrOIrIRBiBKB5ifAr6mGpCVghD8ZIjsLwBIBkA3RU5MCmzLRuGMAKR+CQD4DVwgDW5hDuFwAADab0jANgwhWADQ0otYAAulgIWGgfmHurwgAlwp4NMBQAAfxq8DvqwPQBArzrYaCMoREMSldiEA0CXKoGosQFWPQG3osFXOkPuIsKiPrIQBVJnnhD4Q4VgGYSgSYeMQQI3oWFMaEPPgXKxlJiqutKCCiAVmWH9vIIQHFEiKSK5LzrCIsHqPMQAF4ySHhgANCqgqDOFYBCZxTKGU70CVikzPG+QcT4DwhnZCCYFaAYF8iFyRITIGA0HyDmidSZCHDKAyiGiHCpALKwg8GqEXDEj8aAxonqF6jCG0QQDYCLBOD8YQDyBDpCD5iMB6jmBCANAdFxQVSwjYLUC9TBxMk+AQCbBuBehKAGF4HKD9x+EwjIgeY0HFCdjrRYCMBsBsCEKRh/CkxIjMDAKHAUl6goA0nCB0mLAMlaDkEskA4wp4GclwDUAUAwg8ldH8llKCngDCkV6ilSDimkpSkyng7CDymASKnKkZGUnTAalamgg6nYK9BWAA5UqDBEHGkoDeDmm8lEFWlMI2lSFIginfAiDbSSnSmynumEJelhTQk+kGj4ALZvQF7XADqkkEBvqaB0CLEGTZogBOAmGHBCYSCn6kTQBlgABW2GxQTRNhu6xASRaQA5rRhWPZKZUg/ZLRRhsAbS+W3xmMxGIA8gNhMocUomyGzRg5c5dQbepJaQ9xVkHRiGFUPIQsIAE5xQZ5xgHi2uhCC5Pxr0V6q5Sg65iwomFS55iye5YAB5bRv4J5h4RJYQcxQgV5UgIFuAYF85/GT5pEL5a5DpIQom0koFwUuA+5Q6AFq4QFZULw+ATi4FvZkFMxd5u0D8j5S5fqIQr575+wHg1AKyqFZFP5mFf52FR5sIeFT+WAQcPk+AXZgkxFk5IA/F6QQlCIjOVFz5rGdFDpGUomgUAlkl3Wv5/5XFR6nR0Uhwghlu6gZYMlIlxQel1UhlcF5FXigEMlCFclSF3wil6uKu+ll4kyFlbFWFh5yePFhw+e0ooWwcGoxlUgflP0ZYgVllkKnINlLaK59lwQrQWAomX0/ll4RwBIFo7FGl3lDAewvF4AvOBowgYFMEEFBV1OxVkVBG4x7ltlzy8lvIrQzF/kwuRVMF6lnFOV2l+VEV2eZVvV0ltVsVDVeYom6VQVBgnlOFx5uVHhvlw8AVGVpVJFZErw4VGVsFi5sl9V8VDFzVCkY8bu41GFU1mleF++DYTgWgVIkYwVeUV1N1xYm18Fw1u1jlB1YQD1RKmVp1XVeVvllcxg5lW1d1HApcs2Rlz11FiFb5yFXgSV/kxc4Nrl7lP1HFXl7Rs1OleBt5oR3Md13ReNG1YOpMMVkGcVsNDlCNCkueCyL0aN2VmN2lAIxIKqDA3woAZVJI8g7Ng1W1dViwI1lkomDIPNxxk16N013FWNZArNjAHKbe/Gd1JI8tuVStUN21gtu1ngvUItpICtTAHlktZ1WNaAMJbAPNxKxxy1olYAFtVcigYRsmD5Q15NQt711wPOltdU4tHVGNgFWN+VSIkYT5d1wdwgodGtAtoIQtngHtxQvaIdJ1xtf1bg81qiX81tnNK1mwGdjtfNL1btb11NTUaBmdYRWVnVTN/1xU7CkYn+Zd+dNtxQeK9dudgKvtztlFrt86FN9F8dPCddV4DEedvtld/tuFgdMJsNEA61QVzdUgsJHAc9VVcmZNvd7tJdJoM9aVxN49UtWlNdIAcaJ+ZY1x+ABo6gStC9x9PBZ9rAl96tJN1lPdy5m9kWD9ZwT9+9JtzNhwVZ76qBg6Td2dolADuAQDaO+dUdr1lNo1/k/A7AgDWR0DftB9eFKAxI7CK9fVK1Sg2DA1MDRdcDwt/kdI7Cu9E1aDv9ewSAHg+VMQ+JoN9ABJRDG9xdkWQxSgl4UETDEtjNAd2l++hwYQg+MEygHJYtxQKtTIagVIFoFJ0AewBY2GjST1IAA6nZijyjiIbZFoMasS4VxyQhK+GUkY9tQNugVBeYDQEJuw1wqu1gWgCyFoRAfgbxgEmFHAOhbRpMfgJyJRdUYxBY8aZYIFdUTgcZgV19wAABxjQTNpSgRjgQCTiwSgrAR+5I1UP+GhXA09cJeTWAyheNGOhwiBFUeTBZITrmQg0T2eR+3kyqahGjdxZY2jeYjDEA1RvUsIxJUM0Q76J+RYfYcAZAEhKgkJYz91AJ8AUzYA6gxgcaf5ewUz5j3tewKyRY76HeeYbhoRFTlkzIEIKy2BRykgKyvobRstWAGxykWJmU11Qg0ooREwZ8HQaA1AZ80wMwcgGgzk+hLBeinh0CvgBA7WBk9DaAGUHRvxdsUzzIdBdsJAJAPgquCLlYlAWaw5djAmLBRT76IzXhczgQF90111JLBolYIqZp5QZLCgbRJA3zczMoBcUhrplAEZ8InYBJaCXLXYpA5gFA8BJA1AjaRTGJdGozcg8I9UbwHmzjgkaMRJdzWMyrVL5gqA0QvTaxWM2rkgSA3gPgt+XkAlBc4lziCATFEZ1gGLvUARbj8AEZvOcIDi8j6xagCIQmhEZjdtRYR5wR3jR5Cyn1/GP8Cc8gKayhrpIQhYUlgZMxSQcZtzR5mwHRHmoRzg9F3JOx8JNzkY+bQgSI6pME2CpMBzpMEIpM8OP8pMYg+Y+ZNzfpJbhC5bnjhC1bhCdbDbIASIdSzbD8rbz47bnbnb9bUJNzSAQgpbgEg7KEw7D8NbgEXb47PbJAU7Lbsp87tbo7+Z/9b6PNkJoA1gbeZ9FLJjJZ5B/9UbrwBekA670UBgpAc+NgdUees2FJKIqQ97R0T7eBL7qQNBbTnYMYoA2Cqzszz7r7gH/gRV97mDf7UHs2zrBzoHzTEA/7b7ZYeoru+DaxqHD7dQv7ZEo9HNYlhBEI+VrxWx65f6TmwZj72N4AUAfg2e9HhHjHAREgbTYQbeagOh971z1T9+YTDQ+Y8gAnkHAHs2UhagRKLH97/+CHUnZYsawmX8EeZHBkMJCzCgzrCabHFHxIMozgIDmnP7HHy+XHC+KgvOTeCnKpRYwn8hpH2CinVkWCp4/b5n+V6HiHZ9763xX7/bF1RBGHgHUpdUFJn897IXvnynoBMoX8hW2CsXYXs2BAYQuA4L+HqXfnhepI2K4JMXknmHsb8IBBwXJXgHuH+YzAf6ru4BmnuXynvORXlXNzlns9UpVOdn7XdQWgnwFYRYd7XnDH+VpYwnlQZcTXVXs2RhdUxXSnmHlOOhpJFXOXhwnHs9WgDQCXi3/Xg3Lk3ByXc1GRjnYAKnKhrHp3oXfnoB6grkMXDHgncXmHUhAJ13BHhnRT0hJcgKX6YHhw0AMkEgJ3ozRni0ig+nEHfF0hMB3+/bgn2AQxEQXr0P4PqwjA2l+H3ns3ZYaO9A37Y3ePRKPtRP7HPnaX5lEznnOPxPS3gHdt/G+DYPuPHXgRs9IFvNo3FP/9A3Sh6Q1gTZWPLn5HRHE3F3Yh5P33t3ynr50vRHr3gHwdqi+AY7dPvPQwJ7SvqT/bbnW3ZYJ9bwVR6PbPB39q9AAK+YUSGvMvEvQ3jeuJtvivNgLR9An3L3VPuj+CPPMvOvWx9+MrF7YvjHPZ6g7ZCvFnHPQ3IRovX3RH4Qg3yRgQ/4zvjH9vUh/HvvRHn6AQ+PTgKnuwSQrwuT2fOl0BVOpHEUDtaxillJf6PUWAPZrAaQjit1BHqIJIHJ76NxdsWAyrbHPhLjBHHB021MR0fg1uszsPDQb6FY1oDD5RVcEw1A/QKA0wZABrCAZ8QwOg8gzylvObXRfgNp+WYgaj6vKjYPy0qv1/0BbNWf+HBw2nizlTfBy/ME3wTFfF3bYg7BRVpHb4EgDAw/8V2aQHllLF2DL5TYIAFAB4DIBTALQHxZxLEQtoAkLEkYKkOwhcZFNQioWKxsIDABwAqyWRGsluA0LEC3yoRcGhaERIkEVAsaXAHAHfRuEUmtAoGq8EYFwBIoNgVgAZTxDA9XGSgZvK8TgBL0umGJIQc3lbrCB7oQ9M+jPWKZhFlA0goenAH8AckAUrrRQOwPS4MD30YgklkoKkEVg8A+AJwGIK4YPd8Au5FQVsTUEpAG69AP0uaWbyXIiBoBU4A3WMCkhQcdgmQcQPkAN0SOugssCiEEho8xBbTRCAWBsAGVMm+JDQIYIIDB072rgrYiqjWg2hey6QosF/lcj344AFIdIEIWKphDMKpKOwXkP8AFCiBZxVHG0zLBqAUy6QgIVIWST5g4h0QiIHgHUCWDM8FYKUmpRJC6kywBAogUbzCaH5SUdAtIKCiSCGCUS+AKYWrxmFA05hAKWQWgP1ig40BfQzYGtQiomD7Csgk4eULSHgBhBYwmAHACo7kgXiJg1shADgCiA9QYQqnHiFCEq0Ei1gOADYA5TLDpQqTDIl0OeYJD7oGgiQDoAMo+QZQlsLALMIgCKk1ALw9DvfgUagiSW4IhIb0KG61ETB0AMwRYI0EqovI3g3oukKPxECqRc9VIPW3SE+QAgYgmeqe3PYmCaRJwooccmUK+1Oh8Q/jNAGB6yCS4qQ+ZhiP5E2ChRcAYHoRXYT8YyBfI+gZbRQC3CGAkgykZhXCoyRZBjAeqOwRfaiMsmoQzgQYLoEvAaC8oi0HsIAgWjsm6Q0QVR3NFZMyBdgwkQQAsELlWme4XwU01wGjDwmJ5e6EvzCIjDQswdaAHxyUZwAzBFYE2KSmtEBFmhVoigWYJP6351ALgeMRQKOHqF0BpIBEGWFMpkDrRYNKuCpz45hFrRUhbAKyV2HZj2KsYnFqEI2EmxUR8w8sIQ3CJ4CVhh9aMQQFjG6jdyoYlTuwjEEhYVhI4WIfwJmxCYv4kYdQTYEKrhAn6dA8IZ6wHTPCCK1wmUBUz9FhjXIkYoge3kNoDiJSXY0YeGMPHEDnGhop+taKhFrV6AMBDUAqMxEEBsRywXEUCOgHiilRRYFUTiSPS7pyxuKX8SXyLDTBshZIL1ruUVFRdBRCw+ZjYSx5XJVxHreEJEOPYXcIAXZTQXeIoFHFUgBBdIUb2ZHN5CJnYJAd2IDG5VVRb5HYgOLoIgiDKYI5YNKIgAcpCBs9SoFoBArJJhx4wuALVwICdkeRIY7sWoB+JwBNgFZMofcOCjDjJJzwgLkiBYA/lhxygHNnAHSYqoYCCk7sYJPAaQNsiVE0Yfgy0BCSGg7BAcnCRoF7juhzwhIQH0ty/F7J5ksca7hII3j1yT9YceCNSAAiuUs9HMSuSBp/lSRRArxsN2gEZDSS7VOwfCDq5iwihr6QZp+j/4hSEpSU9IOoOVQ1JMpVwxKZnhymsA8iGUnYCYKKnJSWx/3cqWeNdFEi4Af/HdFUHtE3DE+9qYNrgD4nBRAgzAQ3hzxSmsC1q34+EW9FwD9TRBrhOuqFh4l8SLQfU6IUQKfF6AL+rI4EeNP6lPD7oE0sJjMQWm7SqRKU2ek+IJBkDFpR05HiXzKGjT1Gi07aX1I4B1RP8mFIiQdK2mDTFpToy0cVF2nbSApmg5fMJwfA+FZ6SY36R9IkDEDGkRYfHtyJF7vSlp0YwImtNumIznmTU8ICqjsAQyBpUMxabnx25hBQs3jHAeQLzFdNGkzrJWukXACO5jBMEE4fAFiJ2DOROxWJPlIqnpDORJ9TmfVKuGcjsMIRTSM6JAC0zXizMy4SIJuGNIcSZQvSkiRMEOiYAK9JWTcPQ7v5m84MqWdcOgAAR9if6NkW1L1kBFgeRQY2XAFOKf5CaYsm5vMEll2DGRFk9mUkn87DEGR8wXKZqj/5SZ3ZOsp2XAB2JJA3ZthWmSaIhCxE6B4cm0Pfh/EIiOB+gpgYFTpGMTdyUcxOdpPzG5U6RxojOc0MCY/TQpegrgfmD2m2iyB6crgeh3/SVVc5XAi4gQVplpBkREcouWWGbkNdmBBAA0MiR/KIiW5Xs0kX/xVoSNbRtsgsJ+OtCxE4Jk8voapPHQ1JfZthZiQ5N6HSj6ArkTsFNhmy/icRSQmIHVxCIhzd5s8m0CqiclLyT5PQ/efxgNDONZ6l8leXvL6FM9jkx8sOTDOEBNtp5XQ8CV/OIGEUVZnYxUX/MgnEkVOWcxWj+RAWfzIJdtCqmBVplKTJZikrLs8L2aVxTJoWJSRgMIHGDaZmkwnjEXPGhZCFzw4wfZLIVwBUhs9XnDYSwUKCtJEgN9MHU0C0yZBDsq4QEJkGFjnKis1oWoJ4UFTVBHCISWXNFkCLRFfgTYPJ1pnVC1A0AdEcQqqEd4FFhQvAAsjCb0BSSM2YKCovyGKKiBxQ2ICnJoUmD5FtQuAPUNJCNCkxcilVHsBZlXD3BlgoYRkJkhixzFDinaRHXHn3SOeks/xVDPbrCBzpf0z6btO+l2jNpeM54cnLKHmTEZ/0vlOCRYAXcQZFQpocKXYW7SJZxCxaaILP5rScSJ+aCqSgKU3CilKcgiskgqV6zKS9jXqbksqUoyU5IUupcjPP7VKbiuMwpa0rKF2Lelg4wJbksHFNSQ4N0rhojNJCxJoxgzFOZfNSIwkzsr7Lgjkz1AsJkQewCMlJi7AKprOkJTWLsuwAQQIShCY5acpmYPxjlhsHQvfmhHnKhM2AG8C8WjSItSYxy7gAwGMJIFrlTy05TiVdIfKnl6VadpuE+VqjWAHAPYMCq7ARhFy3wWFdgC2joVHlXYQOG+hLhyZjlLmUXGwBhWARjl2oGemiuwD8B928+GRHaC/hOM2imsB8OuC+WQBEVgEIkg6Eyg6ERJFoTAuFXSAjN4ofK2emkBSHFj3IyIfwHsE1goEFIX8ZbBaFURaFrgRYJpG/G1C0DPhi9Elq4xBXd8xVk5JFdqC4YABNLlX8q7CRoGlxZa+h8pJUwQnhoSJmQ/DyVlseC5y3vqTCpGEIOR2o3MvbIfhujzBuZdCWj3OXsylFHyrEcuA9WzyvVAooUbKU/nFsK2sCz5DOMBTt9k1jAwhN8NXKVtAIHctQIQhqmmxSYHCh+BYsMWEI9+a0QhFVN8hVsHF3bY5Yci6akrI0rwGjkCsJVPKbwJTUldvAuTOJ3iErDHI2QxJ4UFSB46QgSs3CJKnVdXQgV6qjWARkF1y/BkQttBlMWAvy2tmAHzCSR6oismCK8FHUNAFVPxSsJrBxKSr2Y6YdwEKUhIs1cBBPLGqADPVDC6V7Ma9Q6unD3rbSkzOfAAKczvqEQn63KN+s7T6Q/1UhADUMB7LLDKVxgYDcIHPVgbwoOghdr+q9AM4Me8UIiQhqA0alUNl6r9RhtrZYaH1kgQTqcyihvqUNH6kjeBrI1LsKN/6qjZtzq53EU5NGhNCBovWhIIN5Gv4NBpw2CcYWADXhWcyI0MaBNzGzcHeuw2wayI3kBQjBD41ob9oGGzWApso0w9Lhe6dTYxvQ03rcoOmtjXpp3EHtAajzNTfRtA1GbNNM6zkGZpg3saHirq2zcRtk0mbagLm0TVUzEB7rlcZzKpDorTJaE2AAACkVh6gKol4JpJeAoBoAlANgeLZeDQD0AxAAASgtCKl6o0AYLXoFC1yq4ASWmEE8oVS4Sx5Zqk5e+Iq6kwOimypEKRFVJNbbKCKtrXhBnqdaNM11HrTG0pJtam2IQI3v1p+735q2bYM4D5qwA/F1AEYaoqABsAAh6IWwXwRaBsCGQTQQxK6htsVjFBA4YRTAiZW1VdgAVxQdUuVrO0QlcSIAFweACeVMqflBzEAK0ge1dgmVak6FcUEnZXbsAuKuqPiuKBrs/t5KoYpSuKBoBXGKyukcowQAgBdK/AUJecrpCCRt4JawCJgSR0GU021y1HQiCOB7rigvARgJeG4p0jLwsNeEJeGALt4LQ6HHkfDhT7uRh4HjTcKpNWJjta2WTeTsQoaa+h1JpIYOHbWYBpL9GDAeqN7XHndSYCfwcAOJwMBxQCAb5IQMrtwBjbwiFUGqLR1CSlg8VTmgMBUCHWelVEdzTdX9s2XMAq1E0oQPaqdW+NAIMytnZyE9UPwqRTbCNaiXN1iUuwLy9IInT45iNvdPGoQF3U1gh6Yi4sosHBCE20xxtI3b3csIj2gAu6pMCPdEVplXo3yE27tnIy0CE7L+J65mUe2KBHBXcgOngg13wCXh30YAS8D5CLA06kg3FG/BEGgAeArRxQa4tKVmrZAS9UgOkASylK/YUJde2vfXqgBXg8QLemgjAA73RAu9N+aFfED73xRidN+O/GPswoT7G90+2yLPvb2d7F6S+3vRgH70gAjVLAS8AQAgCU7GQFIORmIEvCpBLwKBO/auQFERs3cMkeoUfpwAEAv4xVBHWfrX1SAwdVm5Gm/CUDW99Y0AAAIRpV2KfeNLnHK3Bd7BYFtEeKvp/jI4KVBoSA9AYHjwGYs9AIvD5C56Xg/kQ5NA4vQwNf6EdtMlWtbyxrRFz9l+5gNfvoB36yQD+zCk/pf1v7uanwGwV/svA/74xxQMwYAfraZBaZ6e8/WXoCAN8T8Vemvdvob1T7m9++tvfPpoN0ye9nRbA8UEH3QVh95IZZmobr0aGm9hA7Q3Pr/3d7l9wB8/bwA31HIt9VhyfTYZn06GHDJ+ww7TLy1cb5ZOBSQKwdAPHBy9yhyKGoGr3j7rDe+3QAft0Oul9DThowwPqH1sAR9Fh+I14cSOt77DC+4/QYZX0gGcDrh2/O4csM77NDthpI74eKNpHe9UeyABJvT20zNgKm74BntjLMy5FhGyPXBv4z/8q4jizPfhtGNIb+jYJcHfgbGPF6Ij4BylQQZgPuMEDEYNvMgcQ6oHUjo8+gxkdwNzHrNl4KA2sZgAIHo0zHCfRQaoO7k9jdBrA7TKN79GYSJLHIEMMKYTy1AcQr4/g1KWEhYmhZTlOSUtWdhZkvlaQrEmXC9HwiFZbI2/0uGSMrsoAMTrtvuaj8hAiUDfkIFH7FtNYo/JtgSc4J9tiT+YSdpBqIKcE12lJ0flDtpOcF4dDJ/MNQFCSj8KAbJzgituZMoB8T7MPE0Sf5NcnSTQp/MNGU5NimaTZJ9ABKbaCynWTnaKpnvzjagBsTfbUAMqfhBJrAImpj3Tqbax9tS1bWCk0aa6w0nTTCIekxafhBMmjTlfbU5uCPThA9TjpjeVoENP6nK+Jpz0+EHNM+mtAVp/07af9BlM2sDpzkLqarUGmozXWb066bNMxnLTiZm08mYVPWmOTD8TU9yetO8nkz6/XdtEHuWBEvjaur449NFx/G6SpJBNEjrqi5Y+DiLCAv1A+bwdXEj+xs2RGphUpzAgnEwyMybPUws0l+LAPwENj24d8jcA5GCx/z9RpgkLVsxUgTbI6YIkBZRBmydEzmL4hwXtKbs7JbQ8OnZ9iNCUyBAA

**Comment by davidcelis** [comment]
I've been noticing this for a while too. Not the biggest deal since the protoplasmic phase is relatively short, but none of the upgrades with the "Increases DNA generation from nucleus" effect are working.
