### ISSUE TITLE
[bug] High Population job effects not applying in Antimatter

### ISSUE THREAD

**Issue by PaladinOne** [pmotschmann/Evolve#912]
I was just doing a 4* run as Scorpids on a fresh new world in the Antimatter Universe, and I noticed that my basic jobs (Farmer/Lumberjack/Quarry worker; Soldier; and possibly Miner/Coal miner, Cement worker, Professor, and Scientist but I wasn't paying as close of attention to them) were producing their full resource values, rather than producing at the expected 26% strength. As a result, I had about 4x more basic resources and army strength than I was expecting.

However, Priest, Entertainer, Banker, Craftsmen, and any jobs which applied a % addition to some effect were working at 26% strength as expected.

**Comment by pmotschmann** [comment]
fixed
