### ISSUE TITLE
bug: build queue stuck

### ISSUE THREAD

**Issue by zaquestion** [pmotschmann/Evolve#916]
It would appear that queued items are not getting purchased when they become eligible in the queue. I just started this game a couple days ago, so it's possible I'm misunderstanding the expected behavior... I've attached screenshots below that I think provide more context than anything I'd write through.

Show resources, build cost, and the unactioned build queue
![build_queue_stuck](https://github.com/pmotschmann/Evolve/assets/2358914/b3351cdf-eee9-49a0-88b8-02357a9b9c19)

Screenshot of achievements for progress context
![achievements](https://github.com/pmotschmann/Evolve/assets/2358914/175c81bf-460f-486b-9ec1-4f3fdd912bbb)

**Comment by raisins77** [comment]
Not a bug. Immediately to the right of "Building Queue (1/3)" there is a tiny "||" pause icon. Click it to unpause the queue.

**Comment by zaquestion** [comment]
:facepalm: thx, it does confuse me a bit that "||" means that it's in the paused state rather than "pause this", but I did already notice that with the other queues/buttons and just didn't connect it. :facepalm: :facepalm:
