### ISSUE TITLE
Suggestion: Build queue div should be taller

### ISSUE THREAD

**Issue by chipplyman** [pmotschmann/Evolve#943]
Every time I reload the page (e.g. after rebooting) I go into the DOM inspector and add 100 to the height of the buildQueue div.

Scrolling in the log window is easy.

Scrolling while moving things around in the build queue is super frustrating.

**Comment by fredden** [comment]
I use my mouse to drag to make the box bigger if necessary. Typically it's big enough for me when I load the page.
