### ISSUE TITLE
Some Halloween or something update is broken?

### ISSUE THREAD

**Issue by Crazierinzane** [pmotschmann/Evolve#977]
[https://imgur.com/7mfQY3e](url)
These options do nothing, I think.
Related resources mean nothing now because I cant remember every holiday doodad.

**Comment by Crazierinzane** [comment]
If these buttons are somehow supposed to work, then the issue request is that the options make so little sense that any organic start-finish logic for average players is literally impossible.

**Comment by fredden** [comment]
For reference, this is the linked image:
![7mfQY3e](https://github.com/pmotschmann/Evolve/assets/334786/2205a2bc-b129-46dc-8ca2-2f685f73e8c5)

**Comment by StoneCypher** [comment]
those are just new phrases for "gather food," "gather wood," and "gather stone"

they do things, but if you're not at the very beginning of the game, what they do is so small that you won't be able to see them

you can set `disable special events` until tomorrow if you dislike the halloween event
