### ISSUE TITLE
Market Tab - Alternating Row Colors - Bug

### ISSUE THREAD

**Issue by justino** [pmotschmann/Evolve#98]
Some rows aren't being alternated, see below for example:

![image](https://user-images.githubusercontent.com/224612/58331128-6d4a4c00-7e06-11e9-970b-5355f3f811e5.png)

**Comment by justino** [comment]
Looks like, in between these 2 resources, is `Uranium` which is hidden since I haven't unlocked it in this run.

**Comment by pmotschmann** [comment]
Grrr, so much for the pure CSS solution.
